[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "setuptools_scm[toml]>=3.4"
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "amazon_wishlist_pricewatch/version.py"
version_scheme = "python-simplified-semver"
local_scheme = "no-local-version"
