
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-16T15:06:55+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "6aba287c50d3ac5e5ff85c4f831653e1517b85c9",
 "version": "0.9.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
