
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-14T09:16:25+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "5067141f8798e50fffae1026f7909d496a5ec02b",
 "version": "0.7.0.post.dev190"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
