
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-11T11:44:05-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "5ca9f964c183240be57ef042781fa29883b26c02",
 "version": "4.5.55"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
