
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-15T10:15:09+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "4e90d9a9cdb46eb2b1e7b2dad4ce713debf933e3",
 "version": "2021.6.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
