
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-13T23:11:15+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "2c85525168d0c7f81b256679fe4825cd027df20a",
 "version": "0.1.21"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
