#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

install_requires = \
['flake8']

extras_require = \
{':python_version=="3.6"': ['dataclasses'],
 'dev': ['black', 'mypy', 'tox'],
 'test': ['pytest',
          'pytest-sugar',
          'pytest-coverage',
          'coverage[toml]',
          'types-dataclasses']}

entry_points = \
{'flake8.extension': ['TCI = flake8_typechecking_import:Plugin']}

setup(name='flake8_typechecking_import',
      version='0.5',
      description='A flake plugin that checks for typing.TYPE_CHECKING-able imports',
      author='Adrian Room',
      author_email='ingolemo@gmail.com',
      url='https://github.com/ingolemo/flake8-typechecking_import',
      py_modules=['flake8_typechecking_import'],
      install_requires=install_requires,
      extras_require=extras_require,
      entry_points=entry_points,
      python_requires='>3.6',
     )
