[tool.poetry]
name = "px4test"
version = "1.0.0a4"
description = "Run PX4 falsification tests"
authors = ["Quinn Thibeault <quinn.thibeault96@gmail.com>"]
license = "MIT"
packages = [
    {include = "px4test", from = "src"}
]
include = ["px4test/py.typed"]

[tool.poetry.dependencies]
python = ">=3.7.1, <3.10"
click = "^7.1.2"
pyulog = "^0.9.0"
psy-taliro = "^1.0.0a3"
px4stack = "^1.0.0a1"
px4ctl = "^1.0.0a1"
Sphinx = {version = "^3.5.4", optional = true}
sphinx-autodocgen = {version = "^1.2", optional = true}
sphinx-rtd-theme = {version = "^0.5.2", optional = true}

[tool.poetry.dev-dependencies]
mypy = "^0.812"
black = "^20.8b1"
pytest = "^6.2.3"

[tool.poetry.extras]
docs = ["sphinx", "sphinx-autodocgen", "sphinx-rtd-theme"]

[tool.poetry.scripts]
px4test = "px4test.__main__:px4test"

[tool.black]
line-length = 99

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
