
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-14T07:56:53-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "cf8603b83e93255c4de667f8aa8da2ad1020507c",
 "version": "0.8.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
