
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-14T15:46:39+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "e2d2fdfe5fa804c3f0100a00764d014eb9fa07ad",
 "version": "0.2.16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
