
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-10T13:40:50+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "634ca23cea9bd26bcc7d6ea17af6620d8f2f416f",
 "version": "0.6.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
