
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-13T17:11:27+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "8a1c5239d4dc6237b9a6ebae48f3a14c270ed4f2",
 "version": "2021.05.06post5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
