apiVersion: v1
kind: Secret
metadata:
  name: knox-certbot-secrets
type: Opaque
stringData:
   KNOX_VAULT_APPROLE: {{ required "Vault Approle ID required, .Values.knox.vault.approle" .Values.knox.vault.approle | quote }}
   KNOX_VAULT_SECRET_ID: {{ required "Vault Approle Secret ID required, .Values.knox.vault.approle_secret" .Values.knox.vault.approle_secret | quote }}
   AWS_ACCESS_KEY_ID: {{ required "Vault AWS Access Key ID required, .Values.knox.aws.key" .Values.knox.aws.key | quote }}
   AWS_SECRET_ACCESS_KEY: {{ required "Vault AWS Secret Access Key required, .Values.knox.aws.secret" .Values.knox.aws.secret | quote }}
