
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-12T17:01:04+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "1190a49e48fa415874e9e465d310c67d9824d167",
 "version": "0.24"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
