
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-15T09:32:14+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "d9a1b1dc593641e97d1707c4d8fc4c6a8bab18f8",
 "version": "0.1.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
