
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-14T19:21:57+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "51f3e2ca7e711b1041c0e916d14380f5359e6300",
 "version": "0.4.3b2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
