
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-14T14:19:54+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "f23cc2d5dc477b13c63ffbcfcaed4b37e50a2eb5",
 "version": "2021.05.06post6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
