# Generated by Django 2.2.6 on 2020-12-21 20:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kitchensink', '0012_auto_20201221_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('ui', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('title', models.CharField(help_text='A title for this form', max_length=250, unique=True, verbose_name='Form title')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
