# Generated by Django 2.2.6 on 2020-12-21 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitchensink', '0015_auto_20201221_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formcontent',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contents', related_query_name='contents', to='kitchensink.Form'),
        ),
    ]
