# Generated by Django 2.2.6 on 2021-02-24 19:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kitchensink', '0016_auto_20201221_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('ui', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('title', models.CharField(help_text='A title for this form type', max_length=250, unique=True, verbose_name='Form title')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='formcontent',
            name='form',
        ),
        migrations.DeleteModel(
            name='Form',
        ),
        migrations.AddField(
            model_name='formcontent',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contents', related_query_name='contents', to='kitchensink.FormType'),
        ),
    ]
