# Generated by Django 2.2.6 on 2021-02-24 22:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchensink', '0017_auto_20210224_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formcontent',
            name='author',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
