# Generated by Django 2.2 on 2021-03-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchensink', '0020_auto_20210316_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiedoc',
            name='version',
            field=models.CharField(choices=[('v2', 'v2')], default='v2', help_text='Should be the latest version when created.', max_length=2),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='version',
            field=models.CharField(choices=[('v2', 'v2')], default='v2', help_text='Should be the latest version when created.', max_length=2),
        ),
    ]
