# Generated by Django 2.2 on 2021-06-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchensink', '0023_auto_20210520_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='formcontent',
            name='custom_max_age',
            field=models.IntegerField(blank=True, help_text='Override the default max-age in the Cache-Control header.', max_length=100, null=True),
        ),
    ]
