# Generated by Django 2.2 on 2021-06-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchensink', '0024_formcontent_custom_max_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiedoc',
            name='custom_max_age',
            field=models.IntegerField(blank=True, help_text='Override the default max-age in the Cache-Control header.', null=True),
        ),
        migrations.AddField(
            model_name='sheet',
            name='custom_max_age',
            field=models.IntegerField(blank=True, help_text='Override the default max-age in the Cache-Control header.', null=True),
        ),
        migrations.AlterField(
            model_name='formcontent',
            name='custom_max_age',
            field=models.IntegerField(blank=True, help_text='Override the default max-age in the Cache-Control header.', null=True),
        ),
    ]
