[tool.poetry]
name = "han"
version = "0.1.2"
keywords = [
    "aa",
    "bb",
    "cc",
]
description = "aaaaaaaaaa"
authors = ["piqizhu"]
readme = "README.md"
homepage = "https://github.com/piqizhu/han"
repository = "https://github.com/piqizhu/han"
#documentation = "https://github.com/piqizhu/han"  # 文档地址


[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[[tool.poetry.source]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
