
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-10T05:33:54+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "62dadd95d1e9c35ce2ce022e0b6f55ce690624a6",
 "version": "0.7.0.post.dev172"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
