
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-14T07:16:22+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "e216571de47997a2ef391ec6b7a4ba91cf21df6c",
 "version": "0.7.0.post.dev182"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
