
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-10T22:20:48+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "e43841195d81bc170e1715df012fc35779f7974f",
 "version": "0.1.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
