#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['nchu']

package_data = \
{'': ['*']}

package_dir = \
{'': 'src'}

install_requires = \
['requests >=2.24.0', 'beautifulsoup4 >=4.9.3', 'pandas >=1.1.2']

setup(name='nchu-sdk',
      version='0.2.0',
      description='SDK for accessing NCHU Portal System',
      author='Tomy Hsieh',
      author_email='tomy0000000@gmail.com',
      url='https://github.com/tomy0000000/NCHU-SDK',
      packages=packages,
      package_data=package_data,
      package_dir=package_dir,
      install_requires=install_requires,
      python_requires='~=3.6',
     )
