
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-09T15:48:20+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "7edfdf55e495f9a78a20d2280919d8a78d3fc1e2",
 "version": "0.4.45"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
