
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-09T10:57:21+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "3cd7d387cf5518449df6a92b5c2aadd9ed2d9fc6",
 "version": "0.8.9b0.dev202106100722"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
