#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['jupyterquiz']

package_data = \
{'': ['*']}

setup(name='jupyterquiz',
      version='1.2',
      description='Module to display dynamic quizzes in Jupyter notebooks and Jupyter Books. Uses JavaScript to provide',
      author='John M. Shea',
      author_email='jshea@ieee.org',
      url='http://wireless.ece.ufl.edu/jshea',
      packages=packages,
      package_data=package_data,
     )
