
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-09T09:26:03-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "fb64c5793d2d504da3a31ba34eb37346d7a51084",
 "version": "0.2.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
