
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-10T09:25:42+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "037998f6a4238a51290e31c2efe8d45c417ccff5",
 "version": "0.5.0rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
