[build-system]
requires = ["flit_core >=2,<4",            
            "google-api-python-client==2.4.0",
            "oauth2client==4.1.3",
            "pandas==1.2.4",
            "pygsheets==2.0.5",
            "google-cloud-bigquery==2.16.1",
            "pandas-gbq==0.15.0"
            ]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "googlewrapper"
author = "Jace Iverson"
author-email = "iverson.jace@gmail.com"
home-page = "https://github.com/jaceiverson/google-wrapper"
classifiers = [ "License :: OSI Approved :: MIT License",]
description-file = "README.md"
requires-python = ">=3.6"
