
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-14T16:57:36+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "4a5052a075b2b418af86a9263b45cfcf52ab95ea",
 "version": "2021.05.06post8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
