# Generated by Django 3.2 on 2021-06-02 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('affiliate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affiliatetracker',
            name='session',
        ),
        migrations.AddField(
            model_name='affiliatetracker',
            name='session_key',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Session key'),
        ),
        migrations.AlterField(
            model_name='affiliatetracker',
            name='affiliate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliate_fk', to='affiliate.affiliate'),
        ),
        migrations.AlterField(
            model_name='affiliatetracker',
            name='label',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='label_fk', to='affiliate.label'),
        ),
        migrations.AlterField(
            model_name='affiliatetracker',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_fk', to=settings.AUTH_USER_MODEL),
        ),
    ]
