# Generated by Django 3.2 on 2021-06-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0002_auto_20210602_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='label',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='label',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
