# Generated by Django 3.2 on 2021-06-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0003_auto_20210602_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate',
            name='aid',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True, verbose_name='Affiliate ID'),
        ),
        migrations.AlterField(
            model_name='label',
            name='label',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True, verbose_name='Label ID'),
        ),
    ]
