
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-13T11:51:04-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "69331eb123e7b30eb564d6a84d96e0b38338d90b",
 "version": "2.5.32"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
