# Generated by Django 2.2.17 on 2021-03-24 14:48

from django.db import migrations


def create_domain_settings(apps, schema_editor):
    Domain = apps.get_model('admin', 'Domain')
    DomainSettings = apps.get_model('modoboa_automua', 'DomainSettings')
    for domain in Domain.objects.filter(enabled=True, type='domain'):
        DomainSettings.objects.get_or_create(domain=domain)


class Migration(migrations.Migration):

    dependencies = [
        ('modoboa_automua', '0001_initial'),
        ('admin', '0020_auto_20210130_2226'),
    ]

    operations = [
        migrations.RunPython(create_domain_settings),
    ]
