
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-10T16:12:48-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "ce9ecdac86c8fe33f349f0aa69dfa291540dd688",
 "version": "4.3.40"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
