
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-09T13:38:23-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "ebaf99affbfd84eebc6611e103795b9bd3e4473e",
 "version": "0.0.41"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
