[tool.poetry]
name = 'knada-kafka-consumer'
version = '0.1.11'
description = ''
authors = ['NAV IT dataplattform']
license = 'MIT'

[tool.poetry.dependencies]
python = '^3.7'
google-cloud-storage = '^1.31.2'
google-auth = '^1.22.0'
fastapi = '^0.61.1'
google-cloud-core = '^1.4.1'
google-api-core = '^1.22.2'
uvicorn = '^0.12.1'
kafka-python = '^2.0.2'
google-cloud = '^0.34.0'
google-cloud-bigquery = '^2.1.0'
prometheus_client = '^0.9.0'
pytest = '^6.2.1'
avro-python3 = '^1.10.1'
fastapi-utils = '^0.2.1'

[tool.poetry.dev-dependencies]

[build-system]
requires = ['poetry>=0.12']
build-backend = 'poetry.masonry.api'
