
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-14T08:49:15-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "9b6b2ceaafe6230de33c03c4d15faebf243ecf2e",
 "version": "0.7.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
