[tool.poetry]
name = "quote-manager"
version = "0.4.0"
description = "Helper nlp library for handling non ascii quotes."
authors = ["Sam Havens <sam.havens@writer.com>"]
readme = "README.md"
license = "proprietary"

[tool.poetry.dependencies]
python = "^3.8"
diff-match-patch = "^20181111"

[tool.poetry.dev-dependencies]
pytest = "^5.3.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.pytest.ini_options]
filterwarnings = [
    "error",
    "ignore::DeprecationWarning",
    "ignore::PendingDeprecationWarning",
    "ignore::ImportWarning"
]
testpaths = "tests"
norecursedirs = ".git dist .venv"
