
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-15T13:12:47+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "8e62213b872059c093dc7dfb677db6a759ca868c",
 "version": "0.4.4b2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
