
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-10T18:16:11-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "29d1cbbfc7cab19ee7a6a72167fb51e7addba529",
 "version": "4.3.41"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
