# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spaceone/api/monitoring/plugin/event.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='spaceone/api/monitoring/plugin/event.proto',
  package='spaceone.api.monitoring.plugin',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n*spaceone/api/monitoring/plugin/event.proto\x12\x1espaceone.api.monitoring.plugin\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\"c\n\x0cParseRequest\x12(\n\x07options\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct\x12)\n\x08raw_data\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct\"X\n\x08Resource\x12\x13\n\x0bresource_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x12\n\nip_address\x18\x03 \x01(\t\x12\x15\n\rresource_type\x18\x04 \x01(\t\"\xdf\x02\n\x0b\x45ventResult\x12\x11\n\tevent_key\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x46\n\x08severity\x18\x04 \x01(\x0e\x32\x34.spaceone.api.monitoring.plugin.EventResult.Severity\x12:\n\x08resource\x18\x05 \x01(\x0b\x32(.spaceone.api.monitoring.plugin.Resource\x12\x0c\n\x04rule\x18\x06 \x01(\t\x12%\n\x04tags\x18\x07 \x01(\x0b\x32\x17.google.protobuf.Struct\"`\n\x08Severity\x12\x11\n\rSEVERITY_NONE\x10\x00\x12\x0c\n\x08\x43RITICAL\x10\x01\x12\t\n\x05\x45RROR\x10\x02\x12\x0b\n\x07WARNING\x10\x03\x12\x08\n\x04INFO\x10\x04\x12\x11\n\rNOT_AVAILABLE\x10\x05\"J\n\nEventsInfo\x12<\n\x07results\x18\x01 \x03(\x0b\x32+.spaceone.api.monitoring.plugin.EventResult2l\n\x05\x45vent\x12\x63\n\x05parse\x12,.spaceone.api.monitoring.plugin.ParseRequest\x1a*.spaceone.api.monitoring.plugin.EventsInfo\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,])



_EVENTRESULT_SEVERITY = _descriptor.EnumDescriptor(
  name='Severity',
  full_name='spaceone.api.monitoring.plugin.EventResult.Severity',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SEVERITY_NONE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CRITICAL', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='WARNING', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INFO', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NOT_AVAILABLE', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=584,
  serialized_end=680,
)
_sym_db.RegisterEnumDescriptor(_EVENTRESULT_SEVERITY)


_PARSEREQUEST = _descriptor.Descriptor(
  name='ParseRequest',
  full_name='spaceone.api.monitoring.plugin.ParseRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='options', full_name='spaceone.api.monitoring.plugin.ParseRequest.options', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='raw_data', full_name='spaceone.api.monitoring.plugin.ParseRequest.raw_data', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=236,
)


_RESOURCE = _descriptor.Descriptor(
  name='Resource',
  full_name='spaceone.api.monitoring.plugin.Resource',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='resource_id', full_name='spaceone.api.monitoring.plugin.Resource.resource_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='spaceone.api.monitoring.plugin.Resource.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ip_address', full_name='spaceone.api.monitoring.plugin.Resource.ip_address', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='resource_type', full_name='spaceone.api.monitoring.plugin.Resource.resource_type', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=238,
  serialized_end=326,
)


_EVENTRESULT = _descriptor.Descriptor(
  name='EventResult',
  full_name='spaceone.api.monitoring.plugin.EventResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='event_key', full_name='spaceone.api.monitoring.plugin.EventResult.event_key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='title', full_name='spaceone.api.monitoring.plugin.EventResult.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='spaceone.api.monitoring.plugin.EventResult.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='severity', full_name='spaceone.api.monitoring.plugin.EventResult.severity', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='resource', full_name='spaceone.api.monitoring.plugin.EventResult.resource', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rule', full_name='spaceone.api.monitoring.plugin.EventResult.rule', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tags', full_name='spaceone.api.monitoring.plugin.EventResult.tags', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _EVENTRESULT_SEVERITY,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=329,
  serialized_end=680,
)


_EVENTSINFO = _descriptor.Descriptor(
  name='EventsInfo',
  full_name='spaceone.api.monitoring.plugin.EventsInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='results', full_name='spaceone.api.monitoring.plugin.EventsInfo.results', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=682,
  serialized_end=756,
)

_PARSEREQUEST.fields_by_name['options'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
_PARSEREQUEST.fields_by_name['raw_data'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
_EVENTRESULT.fields_by_name['severity'].enum_type = _EVENTRESULT_SEVERITY
_EVENTRESULT.fields_by_name['resource'].message_type = _RESOURCE
_EVENTRESULT.fields_by_name['tags'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
_EVENTRESULT_SEVERITY.containing_type = _EVENTRESULT
_EVENTSINFO.fields_by_name['results'].message_type = _EVENTRESULT
DESCRIPTOR.message_types_by_name['ParseRequest'] = _PARSEREQUEST
DESCRIPTOR.message_types_by_name['Resource'] = _RESOURCE
DESCRIPTOR.message_types_by_name['EventResult'] = _EVENTRESULT
DESCRIPTOR.message_types_by_name['EventsInfo'] = _EVENTSINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ParseRequest = _reflection.GeneratedProtocolMessageType('ParseRequest', (_message.Message,), {
  'DESCRIPTOR' : _PARSEREQUEST,
  '__module__' : 'spaceone.api.monitoring.plugin.event_pb2'
  # @@protoc_insertion_point(class_scope:spaceone.api.monitoring.plugin.ParseRequest)
  })
_sym_db.RegisterMessage(ParseRequest)

Resource = _reflection.GeneratedProtocolMessageType('Resource', (_message.Message,), {
  'DESCRIPTOR' : _RESOURCE,
  '__module__' : 'spaceone.api.monitoring.plugin.event_pb2'
  # @@protoc_insertion_point(class_scope:spaceone.api.monitoring.plugin.Resource)
  })
_sym_db.RegisterMessage(Resource)

EventResult = _reflection.GeneratedProtocolMessageType('EventResult', (_message.Message,), {
  'DESCRIPTOR' : _EVENTRESULT,
  '__module__' : 'spaceone.api.monitoring.plugin.event_pb2'
  # @@protoc_insertion_point(class_scope:spaceone.api.monitoring.plugin.EventResult)
  })
_sym_db.RegisterMessage(EventResult)

EventsInfo = _reflection.GeneratedProtocolMessageType('EventsInfo', (_message.Message,), {
  'DESCRIPTOR' : _EVENTSINFO,
  '__module__' : 'spaceone.api.monitoring.plugin.event_pb2'
  # @@protoc_insertion_point(class_scope:spaceone.api.monitoring.plugin.EventsInfo)
  })
_sym_db.RegisterMessage(EventsInfo)



_EVENT = _descriptor.ServiceDescriptor(
  name='Event',
  full_name='spaceone.api.monitoring.plugin.Event',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=758,
  serialized_end=866,
  methods=[
  _descriptor.MethodDescriptor(
    name='parse',
    full_name='spaceone.api.monitoring.plugin.Event.parse',
    index=0,
    containing_service=None,
    input_type=_PARSEREQUEST,
    output_type=_EVENTSINFO,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_EVENT)

DESCRIPTOR.services_by_name['Event'] = _EVENT

# @@protoc_insertion_point(module_scope)
