
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-29T21:01:53+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "c5251a477b5dea7a8954ef58f87b8ba356e7f803",
 "version": "0.12.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
