
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "0ad9840b7331bf5790e4f638a35a958b1fdcd664",
 "version": "0.17.31"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
