# Generated by Django 2.2.24 on 2021-06-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_renditions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='original',
            name='href',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rendition',
            name='href',
            field=models.URLField(max_length=255),
        ),
    ]
