[tool]
[tool.poetry]
name = "chromecast_mpris"
version = "0.8.11"
description = "📺 Control Chromecasts from Linux and D-Bus"
license = "AGPL-3.0"
homepage = "https://github.com/alexdelorenzo/chromecast_mpris"
authors = ["Alex DeLorenzo"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.6"
appdirs = ">=1.4.4"
click = ">=8.0.1"
mpris-server = ">=0.2.18"
pychromecast = ">=9.2.0"
pydbus = ">=0.6.0"
pygobject = ">=3.34.0"
cast_control = ">=0.10.8"
