[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.poetry]
name = "model-card-generator"
version = "0.2.0"
description = "ML Model Card generator"
license = "GPLv3"
authors = [
    "Gustavo Salvador <gustavocsalvador@gmail.com>"
]
readme = 'README.md'
repository = "https://github.com/g1stavo/model-card-generator"
homepage = "https://github.com/g1stavo/model-card-generator"

[tool.poetry.dependencies]
python = "~2.7 || ^3.2"
toml = "^0.9"
requests = { version = "^2.13", extras = [ "security" ] }