
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-14T08:51:32+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "50d034091464decead0d96b97c2f9b9d4ab19b3e",
 "version": "0.7.0.post.dev184"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
