
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-14T20:52:39+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "4c89ec254618a3787a33e9b82bcd89caea9f0a84",
 "version": "2021.05.06post10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
