
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-10T20:09:04+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "e8de5e357c0de4a1c67e41021fa7dd1586956833",
 "version": "1.0.6rc4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
