
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-09T15:36:06+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "d223df0e2e15c5c4e481de2e76d4dbfa4a5fcf99",
 "version": "0.4.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
