[tool.poetry]
name = "quick_templates"
version = "1.0.0"
description = "quickly create templates on Pug, Twig, Blade"
authors = ["matyukov stas <matyukov_stas@mail.ru>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
