[tool.poetry]
name = "water_cli"
version = "0.1.0"
description = ""
authors = ["david <davidventura27@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
