# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: f99_erp_api.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='f99_erp_api.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\n\026vn.com.f99.erp-serviceB\nErpService'),
  serialized_pb=_b('\n\x11\x66\x39\x39_erp_api.proto\"T\n\tOrderLine\x12\x0f\n\x07\x62\x61rcode\x18\x01 \x01(\t\x12\x17\n\x0fproduct_uom_qty\x18\x02 \x01(\x05\x12\x1d\n\x15\x66ixed_amount_discount\x18\x03 \x01(\x02\"\x90\x03\n\x15\x43reateSaleOrderParams\x12\x1e\n\norder_line\x18\x01 \x03(\x0b\x32\n.OrderLine\x12\r\n\x05phone\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x14\n\x0cpricelist_id\x18\x04 \x01(\x05\x12\x14\n\x0cwarehouse_id\x18\x05 \x01(\x05\x12\x0e\n\x06street\x18\x06 \x01(\t\x12\x10\n\x08state_id\x18\x07 \x01(\x05\x12\x12\n\ncountry_id\x18\x08 \x01(\x05\x12\x0b\n\x03lat\x18\t \x01(\x02\x12\x0c\n\x04long\x18\n \x01(\x02\x12\x0c\n\x04note\x18\x0b \x01(\t\x12\x1b\n\x13\x61\x64\x64itional_discount\x18\x0c \x01(\x02\x12\x1d\n\x15shipping_address_type\x18\r \x01(\t\x12\x17\n\x0f\x63ommitment_date\x18\x0e \x01(\t\x12\x16\n\x0emarketplace_id\x18\x0f \x01(\x05\x12\x1b\n\x13marketplace_display\x18\x10 \x01(\t\x12\x0f\n\x07trip_id\x18\x11 \x01(\t\x12\x14\n\x0cjournal_name\x18\x12 \x01(\t\"k\n\x15\x43reateSaleOrderResult\x12\x10\n\x08order_id\x18\x01 \x01(\x03\x12\x12\n\norder_name\x18\x02 \x01(\t\x12\x1b\n\x13marketplace_display\x18\x03 \x01(\t\x12\x0f\n\x07trip_id\x18\x04 \x01(\t2\x9b\x01\n\nErpService\x12H\n\x12\x63reate_sale_orders\x12\x16.CreateSaleOrderParams\x1a\x16.CreateSaleOrderResult(\x01\x30\x01\x12\x43\n\x11\x63reate_sale_order\x12\x16.CreateSaleOrderParams\x1a\x16.CreateSaleOrderResultB$\n\x16vn.com.f99.erp-serviceB\nErpServiceb\x06proto3')
)




_ORDERLINE = _descriptor.Descriptor(
  name='OrderLine',
  full_name='OrderLine',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='barcode', full_name='OrderLine.barcode', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='product_uom_qty', full_name='OrderLine.product_uom_qty', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fixed_amount_discount', full_name='OrderLine.fixed_amount_discount', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=105,
)


_CREATESALEORDERPARAMS = _descriptor.Descriptor(
  name='CreateSaleOrderParams',
  full_name='CreateSaleOrderParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='order_line', full_name='CreateSaleOrderParams.order_line', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='phone', full_name='CreateSaleOrderParams.phone', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='CreateSaleOrderParams.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pricelist_id', full_name='CreateSaleOrderParams.pricelist_id', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='warehouse_id', full_name='CreateSaleOrderParams.warehouse_id', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='street', full_name='CreateSaleOrderParams.street', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='state_id', full_name='CreateSaleOrderParams.state_id', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='country_id', full_name='CreateSaleOrderParams.country_id', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lat', full_name='CreateSaleOrderParams.lat', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='long', full_name='CreateSaleOrderParams.long', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='note', full_name='CreateSaleOrderParams.note', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='additional_discount', full_name='CreateSaleOrderParams.additional_discount', index=11,
      number=12, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shipping_address_type', full_name='CreateSaleOrderParams.shipping_address_type', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='commitment_date', full_name='CreateSaleOrderParams.commitment_date', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='marketplace_id', full_name='CreateSaleOrderParams.marketplace_id', index=14,
      number=15, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='marketplace_display', full_name='CreateSaleOrderParams.marketplace_display', index=15,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trip_id', full_name='CreateSaleOrderParams.trip_id', index=16,
      number=17, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='journal_name', full_name='CreateSaleOrderParams.journal_name', index=17,
      number=18, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=508,
)


_CREATESALEORDERRESULT = _descriptor.Descriptor(
  name='CreateSaleOrderResult',
  full_name='CreateSaleOrderResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='order_id', full_name='CreateSaleOrderResult.order_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='order_name', full_name='CreateSaleOrderResult.order_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='marketplace_display', full_name='CreateSaleOrderResult.marketplace_display', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trip_id', full_name='CreateSaleOrderResult.trip_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=510,
  serialized_end=617,
)

_CREATESALEORDERPARAMS.fields_by_name['order_line'].message_type = _ORDERLINE
DESCRIPTOR.message_types_by_name['OrderLine'] = _ORDERLINE
DESCRIPTOR.message_types_by_name['CreateSaleOrderParams'] = _CREATESALEORDERPARAMS
DESCRIPTOR.message_types_by_name['CreateSaleOrderResult'] = _CREATESALEORDERRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OrderLine = _reflection.GeneratedProtocolMessageType('OrderLine', (_message.Message,), {
  'DESCRIPTOR' : _ORDERLINE,
  '__module__' : 'f99_erp_api_pb2'
  # @@protoc_insertion_point(class_scope:OrderLine)
  })
_sym_db.RegisterMessage(OrderLine)

CreateSaleOrderParams = _reflection.GeneratedProtocolMessageType('CreateSaleOrderParams', (_message.Message,), {
  'DESCRIPTOR' : _CREATESALEORDERPARAMS,
  '__module__' : 'f99_erp_api_pb2'
  # @@protoc_insertion_point(class_scope:CreateSaleOrderParams)
  })
_sym_db.RegisterMessage(CreateSaleOrderParams)

CreateSaleOrderResult = _reflection.GeneratedProtocolMessageType('CreateSaleOrderResult', (_message.Message,), {
  'DESCRIPTOR' : _CREATESALEORDERRESULT,
  '__module__' : 'f99_erp_api_pb2'
  # @@protoc_insertion_point(class_scope:CreateSaleOrderResult)
  })
_sym_db.RegisterMessage(CreateSaleOrderResult)


DESCRIPTOR._options = None

_ERPSERVICE = _descriptor.ServiceDescriptor(
  name='ErpService',
  full_name='ErpService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=620,
  serialized_end=775,
  methods=[
  _descriptor.MethodDescriptor(
    name='create_sale_orders',
    full_name='ErpService.create_sale_orders',
    index=0,
    containing_service=None,
    input_type=_CREATESALEORDERPARAMS,
    output_type=_CREATESALEORDERRESULT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='create_sale_order',
    full_name='ErpService.create_sale_order',
    index=1,
    containing_service=None,
    input_type=_CREATESALEORDERPARAMS,
    output_type=_CREATESALEORDERRESULT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ERPSERVICE)

DESCRIPTOR.services_by_name['ErpService'] = _ERPSERVICE

# @@protoc_insertion_point(module_scope)
