
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-17T14:24:12+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "dc14bb0572e4e86a756f555c5188468df95ca9ed",
 "version": "2497"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
