
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-13T16:05:29+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "57642557414a465b3b55dea6a48531d24272d9c7",
 "version": "0.7.13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
