# Generated by Django 3.1.7 on 2021-06-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.TextField(blank=True, null=True)),
                ('name', models.TextField(unique=True)),
                ('is_enabled', models.BooleanField(default=True, verbose_name='enabled')),
            ],
            options={
                'db_table': 'django_command_debug_config',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.TextField(blank=True, editable=False, null=True)),
                ('name', models.TextField(editable=False)),
                ('msg', models.TextField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'django_command_debug_message',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['app'], name='django_comm_app_89a284_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['name'], name='django_comm_name_c83350_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['-created_at'], name='django_comm_created_8068c1_idx'),
        ),
        migrations.AddIndex(
            model_name='config',
            index=models.Index(fields=['app'], name='django_comm_app_b40757_idx'),
        ),
        migrations.AddIndex(
            model_name='config',
            index=models.Index(fields=['name'], name='django_comm_name_75f1c1_idx'),
        ),
    ]
