
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-17T12:15:49+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "13c475b44bc2e0fee34bb9c051215cec2c070e96",
 "version": "0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
