
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-13T20:46:38+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "b70cef9e5c7792a2e20f29335fb5d3b4ea6a3bb5",
 "version": "0.25"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
