[tool.poetry]
authors = ["HackWithHarsha <hackwithharsha@gmail.com>"]
description = ""
name = "hackwithharsha"
readme = "README.md"
version = "0.1.1"

[tool.poetry.dependencies]
python = "^3.6"
typer = {extras = ["all"], version = "^0.3.2"}

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.scripts]
hackwithharsha = "hackwithharsha.main:hello"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
