[tool.poetry]
name = "scTDL"
version = "0.0.6"
description = ""
authors = ["Lequn Wang <wlq762@163.com>"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Science/Research",
  "Natural Language :: English",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Operating System :: MacOS :: MacOS X",
  "Operating System :: Microsoft :: Windows",
  "Operating System :: POSIX :: Linux",
  "Topic :: Scientific/Engineering :: Bio-Informatics",
]
license = "MIT"
packages = [
  {include = "deeptl"},
]
readme = "README.md"

[tool.poetry.dependencies]
anndata = ">=0.7.5"
h5py = ">=2.9.0"
leidenalg = {version = "*", optional = true}
numba = ">=0.41.0"
numpy = ">=1.17.0"
pandas = ">=1.0"
pyscenic = {version = ">=0.11.0,<0.11.2", optional = true}
python = ">=3.7.2,<4.0"
python-igraph = {version = "*", optional = true}
scanpy = {version = ">=1.6", optional = true}
scikit-learn = ">=0.21.2"
scikit-misc = {version = ">=0.1.3", optional = true}
torch = ">=1.7.0"
tqdm = ">=4.56.0"

[tool.poetry.dev-dependencies]
pytest = ">=5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
