
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-11T16:49:52+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "0989fddc03fc88410a31b0d4ea7dff2ef50c3bda",
 "version": "0.12.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
