
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-10T10:00:28-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "b2f83681ca7d6474096fac6d3aa8f5ed04f56dfe",
 "version": "0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
