
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-11T12:54:15+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "a6c3ffb1a21552e0cf990b3ec48594c667a49b78",
 "version": "v0.12.0rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
