language: python

git:
  depth: 25
  quiet: true

python:
  - 3.7
  - 3.8

sudo: false


addons:
  apt:
    packages:
    - python-numpy
    - gfortran 

# env:
#   global:
#     LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so

before_install: 
  - python --version
  - sudo apt install gfortran
  - sudo apt-get install liblapacke-dev checkinstall 
  - sudo apt-get install liblapack-doc checkinstall 
  - export gfortran="/home/kay/gcc-4.8.5/bin/gfortran" 
  - uname -a
  - lsb_release -a  


install:
  - pip install coveralls pytest-cov coverage codecov
  # - python setup.py clean --all build_ext --force --inplace
  - python setup.py develop
  - pip install tox-travis 

script:
  - tox

after_success:
  - coverage combine
  - coverage report
  - coveralls --merge=extension-coveralls.json []
  - coveralls
  - codecov

notifications:
  email:
    on_success: never
    on_failure: always
