
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-11T19:27:49+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "7ba8f5e9f7bf01648ea6ad225f5a7f8f9ae30ef0",
 "version": "2021.05.06post1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
