
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-10T03:48:50+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "b1ee2bcf2252cb622fb0e857b79a80cc774b9ea4",
 "version": "2.2.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
