
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-11T19:37:18+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "ad19f8c90bbbf599e74851da4341e844fdda5d89",
 "version": "2021.05.06post2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
