
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-14T17:39:22+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "1f98793b40e62fd6224085eaf137c80dd1df5ef5",
 "version": "2021.05.06post9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
