[package]
name = "pyawabi"
version = "0.2.2"
authors = ["Hajime Nakagami <nakagami@gmail.com>"]
edition = "2018"

license = "MIT"
description = "A python wrapper for awabi"
repository = "https://github.com/nakagami/pyawabi"
readme = "README.md"
keywords = ["mecab", "awabi"]

[dependencies]
awabi = "0.2"

[dependencies.pyo3]
version = "0.13"
features = ["extension-module"]

[lib]
crate-type = ["cdylib"]
