
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-11T22:16:35+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "1a2d4d0157b96af45ac6f7cf1f1828f3b4cf5269",
 "version": "0.12.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
