from typing import Any

EFI_BOOT_SERVICES_X64: Any
EFI_RUNTIME_SERVICES_X64: Any
EFI_SMM_SYSTEM_TABLE2_X64: Any
BS_PROTOCOLS: Any
BS_PROTOCOLS_INFO_X64: Any
OFFSET_TO_SERVICE: Any
EFI_PEI_SERVICES_X86: Any
