
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-10T07:08:33+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "8b65eec5a0750593426fcca0ebc4185560a3e7d9",
 "version": "0.7.0.post.dev176"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
