stages:
  - image
  - test
  - build
  - publish

ci-image:
  stage: image
  image: docker:20.10-dind
  services:
      - name: docker:20.10-dind
  variables:
      DOCKER_DRIVER: overlay2
  script:
    - 'docker build -t $CI_REGISTRY/linaro/tuxrun/ci -f Dockerfile.ci .'
    - 'docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY'
    - 'docker push $CI_REGISTRY/linaro/tuxrun/ci'
  only:
    refs:
      - master
    changes:
      - Dockerfile.ci

.job:
  image: $CI_REGISTRY/linaro/tuxrun/ci
  script:
    - make $CI_JOB_NAME

unit-tests:
  extends: .job
  stage: test

stylecheck:
  extends: .job
  stage: test

typecheck:
  extends: .job
  stage: test

spellcheck:
  extends: .job
  stage: test

doc:
  extends: .job
  stage: build
  artifacts:
    paths:
      - public
  before_script:
    - python3 -m pip install mkdocs-material  # FIXME not in Debian

pages:
  extends: .job
  stage: publish
  needs:
    - doc
  artifacts:
    paths:
      - public
  only:
    - tags
  script:
    - 'true' # nothing to do

publish-pypi:
  extends: .job
  stage: publish
  only:
    - tags
