
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-16T02:29:26-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "bf42e48e27b07b064940ad649dc469025d3029fb",
 "version": "0.13.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
