
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-12T16:45:05+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "1bf892c12feffe78465d05b63a22b7fe4cd337d5",
 "version": "0.23"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
