# SceneManager Events
BOOT = "BOOT"
READY = "READY"
PRE_UPDATE = "PRE_UPDATE"
POST_UPDATE = "POST_UPDATE"
PRE_STEP = "PRE_STEP"
STEP = "STEP"
POST_STEP = "POST_STEP"
PRE_RENDER = "PRE_RENDER"
POST_RENDER = "POST_RENDER"
RENDER = "RENDER"
TEARDOWN = "TEARDOWN"

# GameObject Events
ADDED_TO_SCENE = "ADDED_TO_SCENE"
REMOVED_FROM_SCENE = "REMOVED_FROM_SCENE"

# Callback Events
SETUP = "SETUP"
PRELOAD = "PRELOAD"
CREATE = "CREATE"
UPDATE = "UPDATE"

# Scene State Events
PAUSE = "PAUSE"
RESUME = "RESUME"
SLEEP = "SLEEP"
WAKE = "WAKE"
STOP = "STOP"
