
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-11T10:46:09-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "db04dc682aee961f942173d02b20cb668ef90faa",
 "version": "3.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
