# Generated by Django 2.2.17 on 2021-03-24 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin', '0020_auto_20210130_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(blank=True, help_text='The server name to use for IMAP, POP and SMTP connections.', max_length=253, verbose_name='Server name')),
                ('use_default', models.BooleanField(default=True, verbose_name='Use default values')),
                ('domain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mua_settings', to='admin.Domain')),
            ],
        ),
    ]
