[package]
name = "pyqec"
version = "0.9.0"
authors = ["maxtremblay <matrem@protonmail.com>"]
edition = "2018"
license = "MIT"

[lib]
name = "pyqec"
crate-type = ["cdylib"]

[dependencies]
bincode = "1.3.3"
ldpc = "0.4.4"
pauli = "0.2.2"
pyo3 = { version = "0.13.2", features = ["extension-module", "abi3-py36"] }
rand = "0.8.3"
rand_xoshiro = { version = "0.6.0", features = ["serde1"] }
serde-pickle = "0.6.2"
serde_json = "1.0.64"
sparse-bin-mat = "0.5.0"

[package.metadata.maturin]
requires-dist = ["multiprocess>=0.70.11", "matplotlib>=3.3.4"]

