[tool.poetry]
name = "pyqec"
version = "0.9.0"
description = ""
authors = ["maxtremblay <matrem@protonmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
matplotlib = "^3.3.4"
multiprocess = "^0.70.11"

[tool.poetry.dev-dependencies]
maturin = "^0.9.0"
pytest = "^6.2.2"
pylint = "^2.7.2"
black = "^20.8b1"
rope = "^0.18.0"
Sphinx = "^3.5.2"
pydata-sphinx-theme = "^0.6.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
