[tool.poetry]
name = "apscheduler_bundle"
version = "2.0.0"
description = "APScheduler support for applauncher"
authors = ["Alvaro Garcia <maxpowel@gmail.com>"]
license = "Apache"

[tool.poetry.dependencies]
python = ">=3.6,<4.0"
applauncher = "^2.0.2"
APScheduler = "^3.7.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
