
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-16T11:47:07+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "abf6ce3ddeac2c851fd09765f6a585fc2e20f2ae",
 "version": "0.1.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
