info = {"message": "Add abs imports (#1057)", "commit": "c5337391f0d62070732e50968531493961ded6b7", "date": "2021-06-14 23:09:28 +0100", "branch": "release/1.0.2-post", "version": "1.0.2+4.gc5337391"}

# This file is automatically generated by version.py
# Do not include it to git!
