[build-system]
requires = ["setuptools>=40.8.0", "wheel", "Cython>=0.29.23"]
build-backend = "setuptools.build_meta"

[tool.flake8]
exclude = ".git,__pycache__,docs/source/conf.py,old,build,dist"
max-line-length = 90
