# coding: utf-8

"""
    Aron API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from openapi_client.configuration import Configuration


class ModelBillingHistoryEdges(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'experiment': 'ModelExperiment',
        'organization': 'ModelOrganization',
        'service': 'ModelService'
    }

    attribute_map = {
        'experiment': 'experiment',
        'organization': 'organization',
        'service': 'service'
    }

    def __init__(self, experiment=None, organization=None, service=None, local_vars_configuration=None):  # noqa: E501
        """ModelBillingHistoryEdges - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._experiment = None
        self._organization = None
        self._service = None
        self.discriminator = None

        if experiment is not None:
            self.experiment = experiment
        if organization is not None:
            self.organization = organization
        if service is not None:
            self.service = service

    @property
    def experiment(self):
        """Gets the experiment of this ModelBillingHistoryEdges.  # noqa: E501


        :return: The experiment of this ModelBillingHistoryEdges.  # noqa: E501
        :rtype: ModelExperiment
        """
        return self._experiment

    @experiment.setter
    def experiment(self, experiment):
        """Sets the experiment of this ModelBillingHistoryEdges.


        :param experiment: The experiment of this ModelBillingHistoryEdges.  # noqa: E501
        :type experiment: ModelExperiment
        """

        self._experiment = experiment

    @property
    def organization(self):
        """Gets the organization of this ModelBillingHistoryEdges.  # noqa: E501


        :return: The organization of this ModelBillingHistoryEdges.  # noqa: E501
        :rtype: ModelOrganization
        """
        return self._organization

    @organization.setter
    def organization(self, organization):
        """Sets the organization of this ModelBillingHistoryEdges.


        :param organization: The organization of this ModelBillingHistoryEdges.  # noqa: E501
        :type organization: ModelOrganization
        """

        self._organization = organization

    @property
    def service(self):
        """Gets the service of this ModelBillingHistoryEdges.  # noqa: E501


        :return: The service of this ModelBillingHistoryEdges.  # noqa: E501
        :rtype: ModelService
        """
        return self._service

    @service.setter
    def service(self, service):
        """Sets the service of this ModelBillingHistoryEdges.


        :param service: The service of this ModelBillingHistoryEdges.  # noqa: E501
        :type service: ModelService
        """

        self._service = service

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ModelBillingHistoryEdges):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ModelBillingHistoryEdges):
            return True

        return self.to_dict() != other.to_dict()
