# coding: utf-8

"""
    Aron API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from openapi_client.configuration import Configuration


class ServiceUpdateAPIPayload(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'cluster_node_ids': 'list[int]',
        'env_vars': 'list[ModelEnvVar]',
        'name': 'str',
        'ports': 'list[ModelServicePort]',
        'resource_spec': 'ModelKernelResourceSpecField',
        'resource_spec_id': 'int',
        'ssh_credentials_id': 'int',
        'start_command': 'str'
    }

    attribute_map = {
        'cluster_node_ids': 'cluster_node_ids',
        'env_vars': 'env_vars',
        'name': 'name',
        'ports': 'ports',
        'resource_spec': 'resource_spec',
        'resource_spec_id': 'resource_spec_id',
        'ssh_credentials_id': 'ssh_credentials_id',
        'start_command': 'start_command'
    }

    def __init__(self, cluster_node_ids=None, env_vars=None, name=None, ports=None, resource_spec=None, resource_spec_id=None, ssh_credentials_id=None, start_command=None, local_vars_configuration=None):  # noqa: E501
        """ServiceUpdateAPIPayload - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._cluster_node_ids = None
        self._env_vars = None
        self._name = None
        self._ports = None
        self._resource_spec = None
        self._resource_spec_id = None
        self._ssh_credentials_id = None
        self._start_command = None
        self.discriminator = None

        if cluster_node_ids is not None:
            self.cluster_node_ids = cluster_node_ids
        if env_vars is not None:
            self.env_vars = env_vars
        self.name = name
        if ports is not None:
            self.ports = ports
        if resource_spec is not None:
            self.resource_spec = resource_spec
        self.resource_spec_id = resource_spec_id
        self.ssh_credentials_id = ssh_credentials_id
        self.start_command = start_command

    @property
    def cluster_node_ids(self):
        """Gets the cluster_node_ids of this ServiceUpdateAPIPayload.  # noqa: E501


        :return: The cluster_node_ids of this ServiceUpdateAPIPayload.  # noqa: E501
        :rtype: list[int]
        """
        return self._cluster_node_ids

    @cluster_node_ids.setter
    def cluster_node_ids(self, cluster_node_ids):
        """Sets the cluster_node_ids of this ServiceUpdateAPIPayload.


        :param cluster_node_ids: The cluster_node_ids of this ServiceUpdateAPIPayload.  # noqa: E501
        :type cluster_node_ids: list[int]
        """

        self._cluster_node_ids = cluster_node_ids

    @property
    def env_vars(self):
        """Gets the env_vars of this ServiceUpdateAPIPayload.  # noqa: E501


        :return: The env_vars of this ServiceUpdateAPIPayload.  # noqa: E501
        :rtype: list[ModelEnvVar]
        """
        return self._env_vars

    @env_vars.setter
    def env_vars(self, env_vars):
        """Sets the env_vars of this ServiceUpdateAPIPayload.


        :param env_vars: The env_vars of this ServiceUpdateAPIPayload.  # noqa: E501
        :type env_vars: list[ModelEnvVar]
        """

        self._env_vars = env_vars

    @property
    def name(self):
        """Gets the name of this ServiceUpdateAPIPayload.  # noqa: E501


        :return: The name of this ServiceUpdateAPIPayload.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ServiceUpdateAPIPayload.


        :param name: The name of this ServiceUpdateAPIPayload.  # noqa: E501
        :type name: str
        """

        self._name = name

    @property
    def ports(self):
        """Gets the ports of this ServiceUpdateAPIPayload.  # noqa: E501


        :return: The ports of this ServiceUpdateAPIPayload.  # noqa: E501
        :rtype: list[ModelServicePort]
        """
        return self._ports

    @ports.setter
    def ports(self, ports):
        """Sets the ports of this ServiceUpdateAPIPayload.


        :param ports: The ports of this ServiceUpdateAPIPayload.  # noqa: E501
        :type ports: list[ModelServicePort]
        """

        self._ports = ports

    @property
    def resource_spec(self):
        """Gets the resource_spec of this ServiceUpdateAPIPayload.  # noqa: E501


        :return: The resource_spec of this ServiceUpdateAPIPayload.  # noqa: E501
        :rtype: ModelKernelResourceSpecField
        """
        return self._resource_spec

    @resource_spec.setter
    def resource_spec(self, resource_spec):
        """Sets the resource_spec of this ServiceUpdateAPIPayload.


        :param resource_spec: The resource_spec of this ServiceUpdateAPIPayload.  # noqa: E501
        :type resource_spec: ModelKernelResourceSpecField
        """

        self._resource_spec = resource_spec

    @property
    def resource_spec_id(self):
        """Gets the resource_spec_id of this ServiceUpdateAPIPayload.  # noqa: E501


        :return: The resource_spec_id of this ServiceUpdateAPIPayload.  # noqa: E501
        :rtype: int
        """
        return self._resource_spec_id

    @resource_spec_id.setter
    def resource_spec_id(self, resource_spec_id):
        """Sets the resource_spec_id of this ServiceUpdateAPIPayload.


        :param resource_spec_id: The resource_spec_id of this ServiceUpdateAPIPayload.  # noqa: E501
        :type resource_spec_id: int
        """

        self._resource_spec_id = resource_spec_id

    @property
    def ssh_credentials_id(self):
        """Gets the ssh_credentials_id of this ServiceUpdateAPIPayload.  # noqa: E501


        :return: The ssh_credentials_id of this ServiceUpdateAPIPayload.  # noqa: E501
        :rtype: int
        """
        return self._ssh_credentials_id

    @ssh_credentials_id.setter
    def ssh_credentials_id(self, ssh_credentials_id):
        """Sets the ssh_credentials_id of this ServiceUpdateAPIPayload.


        :param ssh_credentials_id: The ssh_credentials_id of this ServiceUpdateAPIPayload.  # noqa: E501
        :type ssh_credentials_id: int
        """

        self._ssh_credentials_id = ssh_credentials_id

    @property
    def start_command(self):
        """Gets the start_command of this ServiceUpdateAPIPayload.  # noqa: E501


        :return: The start_command of this ServiceUpdateAPIPayload.  # noqa: E501
        :rtype: str
        """
        return self._start_command

    @start_command.setter
    def start_command(self, start_command):
        """Sets the start_command of this ServiceUpdateAPIPayload.


        :param start_command: The start_command of this ServiceUpdateAPIPayload.  # noqa: E501
        :type start_command: str
        """

        self._start_command = start_command

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ServiceUpdateAPIPayload):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ServiceUpdateAPIPayload):
            return True

        return self.to_dict() != other.to_dict()
