
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-16T09:51:16+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "24a69308d3105da6b266f175c100ada5da8d9fc1",
 "version": "v0.12.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
