
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-15T21:45:31-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "521e8d718713d19d2159de8c58258ccbf7c0b647",
 "version": "0.8.301"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
