[tool.poetry]
name = "pykefile"
version = "0.0.1a"
description = "Make-like build tool for Python projects"
authors = ["frissyn"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
click = "^8.0.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
