
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-08T10:08:05-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "c3ad19db508d54455990c9b6729f0039f935d333",
 "version": "2021.6.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
