
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-10T15:47:06+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "4f9ad4898feb3e43a29b0d6b321b572ce03cd02e",
 "version": "2491"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
