[tool.poetry]
name = "query_ec2_metadata"
version = "0.1.3"
description = "Allows querying EC2 instance metadata"
authors = ["HMRC WebOps"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/hmrc/ec2_metadata"

[tool.poetry.dependencies]
python = ">=3.6.2,<4.0"
requests = "^2.25.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
black = "^21.6b0"
httpretty = "^1.1.3"
bandit = "^1.7.0"
safety = "^1.10.3"
mock = "^4.0.3"
mypy = "^0.902"
flake8 = "^3.9.2"
pycodestyle = "^2.7.0"

[tool.poetry.scripts]
ec2-metadata = 'query_ec2_metadata:main'
instance-identity = 'query_ec2_metadata:main'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
