[tool.poetry]
name = "lawnmower"
version = "0.0.1-beta"
description = "LAWNMOWER - Simple Python task runner"
authors = ["arnu515 <arnu515@protonmail.com>"]
license = "GPL-3.0-only"
classifiers = [
  "Development Status :: 4 - Beta",
  "Environment :: Console",
  "Intended Audience :: Developers",
  "License :: Other/Proprietary License",
  "Natural Language :: English",
  "Topic :: Software Development",
  "Typing :: Typed"
]
keywords = ["build system", "make", "mow", "task runner", "scripts"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
flake8 = "^3.9.2"
pylint = "^2.8.3"
mypy = "^0.902"
yapf = "^0.31.0"

[tool.poetry.scripts]
lawnmower = "lawnmower:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.yapf]
align_closing_bracket_with_visual_indent = false
allow_multiline_lambdas = false
allow_multiline_dictionary_keys = false
blank_line_before_nested_class_or_def = true
blank_line_before_module_docstring = false
blank_line_before_class_docstring = true
blank_lines_around_top_level_definition = 2
blank_lines_between_top_level_imports_and_variables = 2
column_limit = 80
dedent_closing_brackets = true
coalesce_brackets = true
each_dict_entry_on_separate_line = true
indent_dictionary_value = true
indent_width = 4
indent_blank_lines = false
join_multiple_lines = true
spaces_around_subscript_colon = false
spaces_before_comment = 2
space_between_ending_comma_and_closing_bracket = true
split_before_closing_bracket = true
split_before_dict_set_generator = true

[mypy]
python_version = 3.8
files = "*.py"
disallow_untyped_defs = true
disallow_incomplete_defs = true
no_implicit_optional = true
warn_unused_ignores = true
warn_redundant_casts = true
show_error_context = true
show_column_numbers = true
show_error_codes = true
pretty = true
