# Generated by Django 2.0.7 on 2018-11-04 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20180903_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(max_length=255, upload_to='reviews', verbose_name='File')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordering')),
            ],
            options={
                'verbose_name': 'Review image',
                'verbose_name_plural': 'Review images',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RemoveField(
            model_name='review',
            name='photo',
        ),
        migrations.AddField(
            model_name='reviewimage',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reviews.Review', verbose_name='Review'),
        ),
    ]
