[tool.poetry]
name = "aiohttp-sqlalchemy"
version = "0.13.0"
description = "SQLAlchemy 1.4 / 2.0 support for aiohttp."
authors = [
    "Ruslan Ilyasovich Gilfanov <ri.gilfanov@yandex.ru>",
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Topic :: Internet",
    "Topic :: Internet :: WWW/HTTP",
]
keywords = ["aiohttp", "sqlalchemy"]
license = "BSD-3-Clause"
readme = "README.rst"

documentation = "https://aiohttp-sqlalchemy.readthedocs.io/"
homepage = "https://github.com/ri-gilfanov/aiohttp-sqlalchemy"
repository = "https://github.com/ri-gilfanov/aiohttp-sqlalchemy"

[tool.coverage.report]
exclude_lines = [
    "if TYPE_CHECKING",
]

[tool.poetry.dependencies]
python = "^3.7"
aiohttp = "^3.7.4.post0"
SQLAlchemy = "^1.4.18"

[tool.poetry.dev-dependencies]
asyncpg = ">=0.23.0"
aiosqlite = ">=0.17.0"
mypy = ">=0.902"
pytest = ">=6.2.4"
pytest-cov = ">=2.12.1"
Sphinx = ">=4.0.2"
sphinx_rtd_theme = ">=0.5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
