
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-15T08:35:37+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "6e028c21f9316893f774afffdd319797d359e7d2",
 "version": "2494"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
