# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: ^(tests/data/)

default_language_version:
  python: python3.9

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: no-commit-to-branch
        args: [--branch, master]

  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.0
    hooks:
      - id: flake8
        # additional_dependencies: [flake8-bugbear]
        files: src/

  - repo: local
    hooks:
      - id: check-copyright
        name: check-copyright
        entry: ./lb-check-copyright
        language: script
        files: ''
        pass_filenames: false
