
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-17T10:53:28+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "f7e09069b2ab235d3e01ecbbf751534b83f901e7",
 "version": "v1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
