
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-10T06:56:49+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "33e24d3b0b836b0489f742043df3f2468c8209bd",
 "version": "0.7.0.post.dev174"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
