
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-11T10:03:05+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "0deab4479d187b08f894ce3b002da42d799492d5",
 "version": "2492"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
