
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-15T16:55:37+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "50f12fd21ee70ab04bc94c5ce1a50de702086201",
 "version": "2021.05.06post13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
