[tool.poetry]
name = "graphene-pydantic-updated"
version = "0.1.0"
description = ""
authors = ["Jeremy Berman <jerber@sas.upenn.edu>"]

[tool.poetry.dependencies]
python = "^3.7"
# To keep things simple, we only support newer versions of Graphene & Pydantic
graphene = ">=3.0b5"
pydantic = "^1.8.1"


[tool.poetry.dev-dependencies]
pytest = "~4.6.4"
pytest-cov = "~2.7.1"
tox = "~3.12.0"  # sync with tox.ini
mypy = "0.720"
black = "20.8b1"
pre-commit = "~1.17.0"
tox-gh-actions = "^1.3.0"
# https://github.com/python-poetry/poetry/issues/2386
dataclasses = { version = "^0.6", python = "^3.6.1, <3.7" }

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
