# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: metric_configuration.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='metric_configuration.proto',
  package='metricrule.config.api',
  syntax='proto3',
  serialized_options=b'Z5github.com/metricrule-config-api/proto/metricconfigpb',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1ametric_configuration.proto\x12\x15metricrule.config.api\"\x8c\x02\n\rSidecarConfig\x12:\n\rinput_metrics\x18\x01 \x03(\x0b\x32#.metricrule.config.api.MetricConfig\x12;\n\x0eoutput_metrics\x18\x02 \x03(\x0b\x32#.metricrule.config.api.MetricConfig\x12\x45\n\x19\x63ontext_labels_from_input\x18\x03 \x03(\x0b\x32\".metricrule.config.api.LabelConfig\x12\x1c\n\x14input_content_filter\x18\x04 \x01(\t\x12\x1d\n\x15output_content_filter\x18\x05 \x01(\t\"\xd5\x01\n\x0cMetricConfig\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x32\n\x06labels\x18\x02 \x03(\x0b\x32\".metricrule.config.api.LabelConfig\x12\x44\n\x0esimple_counter\x18\x64 \x01(\x0b\x32*.metricrule.config.api.SimpleCounterMetricH\x00\x12\x33\n\x05value\x18\x65 \x01(\x0b\x32\".metricrule.config.api.ValueMetricH\x00\x42\x08\n\x06metric\"\x15\n\x13SimpleCounterMetric\"@\n\x0bValueMetric\x12\x31\n\x05value\x18\x01 \x01(\x0b\x32\".metricrule.config.api.ValueConfig\"}\n\x0bLabelConfig\x12\x35\n\tlabel_key\x18\x01 \x01(\x0b\x32\".metricrule.config.api.ValueConfig\x12\x37\n\x0blabel_value\x18\x02 \x01(\x0b\x32\".metricrule.config.api.ValueConfig\"\x9f\x01\n\x0bValueConfig\x12\x38\n\x0cparsed_value\x18\x01 \x01(\x0b\x32\".metricrule.config.api.ParsedValue\x12\x16\n\x0cstring_value\x18\x64 \x01(\tH\x00\x12\x17\n\rinteger_value\x18\x65 \x01(\x03H\x00\x12\x15\n\x0b\x66loat_value\x18\x66 \x01(\x02H\x00\x42\x0e\n\x0cstatic_value\"\xa4\x01\n\x0bParsedValue\x12\x12\n\nfield_path\x18\x01 \x01(\t\x12\x42\n\x0bparsed_type\x18\x02 \x01(\x0e\x32-.metricrule.config.api.ParsedValue.ParsedType\"=\n\nParsedType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\n\n\x06STRING\x10\x01\x12\x0b\n\x07INTEGER\x10\x02\x12\t\n\x05\x46LOAT\x10\x03\x42\x37Z5github.com/metricrule-config-api/proto/metricconfigpbb\x06proto3'
)



_PARSEDVALUE_PARSEDTYPE = _descriptor.EnumDescriptor(
  name='ParsedType',
  full_name='metricrule.config.api.ParsedValue.ParsedType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STRING', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INTEGER', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FLOAT', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=1022,
  serialized_end=1083,
)
_sym_db.RegisterEnumDescriptor(_PARSEDVALUE_PARSEDTYPE)


_SIDECARCONFIG = _descriptor.Descriptor(
  name='SidecarConfig',
  full_name='metricrule.config.api.SidecarConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='input_metrics', full_name='metricrule.config.api.SidecarConfig.input_metrics', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='output_metrics', full_name='metricrule.config.api.SidecarConfig.output_metrics', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='context_labels_from_input', full_name='metricrule.config.api.SidecarConfig.context_labels_from_input', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='input_content_filter', full_name='metricrule.config.api.SidecarConfig.input_content_filter', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='output_content_filter', full_name='metricrule.config.api.SidecarConfig.output_content_filter', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=322,
)


_METRICCONFIG = _descriptor.Descriptor(
  name='MetricConfig',
  full_name='metricrule.config.api.MetricConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='metricrule.config.api.MetricConfig.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='labels', full_name='metricrule.config.api.MetricConfig.labels', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='simple_counter', full_name='metricrule.config.api.MetricConfig.simple_counter', index=2,
      number=100, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='metricrule.config.api.MetricConfig.value', index=3,
      number=101, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='metric', full_name='metricrule.config.api.MetricConfig.metric',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=325,
  serialized_end=538,
)


_SIMPLECOUNTERMETRIC = _descriptor.Descriptor(
  name='SimpleCounterMetric',
  full_name='metricrule.config.api.SimpleCounterMetric',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=540,
  serialized_end=561,
)


_VALUEMETRIC = _descriptor.Descriptor(
  name='ValueMetric',
  full_name='metricrule.config.api.ValueMetric',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='metricrule.config.api.ValueMetric.value', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=563,
  serialized_end=627,
)


_LABELCONFIG = _descriptor.Descriptor(
  name='LabelConfig',
  full_name='metricrule.config.api.LabelConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='label_key', full_name='metricrule.config.api.LabelConfig.label_key', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='label_value', full_name='metricrule.config.api.LabelConfig.label_value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=629,
  serialized_end=754,
)


_VALUECONFIG = _descriptor.Descriptor(
  name='ValueConfig',
  full_name='metricrule.config.api.ValueConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='parsed_value', full_name='metricrule.config.api.ValueConfig.parsed_value', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='string_value', full_name='metricrule.config.api.ValueConfig.string_value', index=1,
      number=100, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='integer_value', full_name='metricrule.config.api.ValueConfig.integer_value', index=2,
      number=101, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='float_value', full_name='metricrule.config.api.ValueConfig.float_value', index=3,
      number=102, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='static_value', full_name='metricrule.config.api.ValueConfig.static_value',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=757,
  serialized_end=916,
)


_PARSEDVALUE = _descriptor.Descriptor(
  name='ParsedValue',
  full_name='metricrule.config.api.ParsedValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='field_path', full_name='metricrule.config.api.ParsedValue.field_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='parsed_type', full_name='metricrule.config.api.ParsedValue.parsed_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PARSEDVALUE_PARSEDTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=919,
  serialized_end=1083,
)

_SIDECARCONFIG.fields_by_name['input_metrics'].message_type = _METRICCONFIG
_SIDECARCONFIG.fields_by_name['output_metrics'].message_type = _METRICCONFIG
_SIDECARCONFIG.fields_by_name['context_labels_from_input'].message_type = _LABELCONFIG
_METRICCONFIG.fields_by_name['labels'].message_type = _LABELCONFIG
_METRICCONFIG.fields_by_name['simple_counter'].message_type = _SIMPLECOUNTERMETRIC
_METRICCONFIG.fields_by_name['value'].message_type = _VALUEMETRIC
_METRICCONFIG.oneofs_by_name['metric'].fields.append(
  _METRICCONFIG.fields_by_name['simple_counter'])
_METRICCONFIG.fields_by_name['simple_counter'].containing_oneof = _METRICCONFIG.oneofs_by_name['metric']
_METRICCONFIG.oneofs_by_name['metric'].fields.append(
  _METRICCONFIG.fields_by_name['value'])
_METRICCONFIG.fields_by_name['value'].containing_oneof = _METRICCONFIG.oneofs_by_name['metric']
_VALUEMETRIC.fields_by_name['value'].message_type = _VALUECONFIG
_LABELCONFIG.fields_by_name['label_key'].message_type = _VALUECONFIG
_LABELCONFIG.fields_by_name['label_value'].message_type = _VALUECONFIG
_VALUECONFIG.fields_by_name['parsed_value'].message_type = _PARSEDVALUE
_VALUECONFIG.oneofs_by_name['static_value'].fields.append(
  _VALUECONFIG.fields_by_name['string_value'])
_VALUECONFIG.fields_by_name['string_value'].containing_oneof = _VALUECONFIG.oneofs_by_name['static_value']
_VALUECONFIG.oneofs_by_name['static_value'].fields.append(
  _VALUECONFIG.fields_by_name['integer_value'])
_VALUECONFIG.fields_by_name['integer_value'].containing_oneof = _VALUECONFIG.oneofs_by_name['static_value']
_VALUECONFIG.oneofs_by_name['static_value'].fields.append(
  _VALUECONFIG.fields_by_name['float_value'])
_VALUECONFIG.fields_by_name['float_value'].containing_oneof = _VALUECONFIG.oneofs_by_name['static_value']
_PARSEDVALUE.fields_by_name['parsed_type'].enum_type = _PARSEDVALUE_PARSEDTYPE
_PARSEDVALUE_PARSEDTYPE.containing_type = _PARSEDVALUE
DESCRIPTOR.message_types_by_name['SidecarConfig'] = _SIDECARCONFIG
DESCRIPTOR.message_types_by_name['MetricConfig'] = _METRICCONFIG
DESCRIPTOR.message_types_by_name['SimpleCounterMetric'] = _SIMPLECOUNTERMETRIC
DESCRIPTOR.message_types_by_name['ValueMetric'] = _VALUEMETRIC
DESCRIPTOR.message_types_by_name['LabelConfig'] = _LABELCONFIG
DESCRIPTOR.message_types_by_name['ValueConfig'] = _VALUECONFIG
DESCRIPTOR.message_types_by_name['ParsedValue'] = _PARSEDVALUE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SidecarConfig = _reflection.GeneratedProtocolMessageType('SidecarConfig', (_message.Message,), {
  'DESCRIPTOR' : _SIDECARCONFIG,
  '__module__' : 'metric_configuration_pb2'
  # @@protoc_insertion_point(class_scope:metricrule.config.api.SidecarConfig)
  })
_sym_db.RegisterMessage(SidecarConfig)

MetricConfig = _reflection.GeneratedProtocolMessageType('MetricConfig', (_message.Message,), {
  'DESCRIPTOR' : _METRICCONFIG,
  '__module__' : 'metric_configuration_pb2'
  # @@protoc_insertion_point(class_scope:metricrule.config.api.MetricConfig)
  })
_sym_db.RegisterMessage(MetricConfig)

SimpleCounterMetric = _reflection.GeneratedProtocolMessageType('SimpleCounterMetric', (_message.Message,), {
  'DESCRIPTOR' : _SIMPLECOUNTERMETRIC,
  '__module__' : 'metric_configuration_pb2'
  # @@protoc_insertion_point(class_scope:metricrule.config.api.SimpleCounterMetric)
  })
_sym_db.RegisterMessage(SimpleCounterMetric)

ValueMetric = _reflection.GeneratedProtocolMessageType('ValueMetric', (_message.Message,), {
  'DESCRIPTOR' : _VALUEMETRIC,
  '__module__' : 'metric_configuration_pb2'
  # @@protoc_insertion_point(class_scope:metricrule.config.api.ValueMetric)
  })
_sym_db.RegisterMessage(ValueMetric)

LabelConfig = _reflection.GeneratedProtocolMessageType('LabelConfig', (_message.Message,), {
  'DESCRIPTOR' : _LABELCONFIG,
  '__module__' : 'metric_configuration_pb2'
  # @@protoc_insertion_point(class_scope:metricrule.config.api.LabelConfig)
  })
_sym_db.RegisterMessage(LabelConfig)

ValueConfig = _reflection.GeneratedProtocolMessageType('ValueConfig', (_message.Message,), {
  'DESCRIPTOR' : _VALUECONFIG,
  '__module__' : 'metric_configuration_pb2'
  # @@protoc_insertion_point(class_scope:metricrule.config.api.ValueConfig)
  })
_sym_db.RegisterMessage(ValueConfig)

ParsedValue = _reflection.GeneratedProtocolMessageType('ParsedValue', (_message.Message,), {
  'DESCRIPTOR' : _PARSEDVALUE,
  '__module__' : 'metric_configuration_pb2'
  # @@protoc_insertion_point(class_scope:metricrule.config.api.ParsedValue)
  })
_sym_db.RegisterMessage(ParsedValue)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
