# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import f99_erp_api_pb2 as f99__erp__api__pb2


class F99ErpApiStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.create_sale_order = channel.stream_stream(
        '/f99_erp_api.F99ErpApi/create_sale_order',
        request_serializer=f99__erp__api__pb2.CreateSaleOrderParams.SerializeToString,
        response_deserializer=f99__erp__api__pb2.CreateSaleOrderResult.FromString,
        )


class F99ErpApiServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def create_sale_order(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_F99ErpApiServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'create_sale_order': grpc.stream_stream_rpc_method_handler(
          servicer.create_sale_order,
          request_deserializer=f99__erp__api__pb2.CreateSaleOrderParams.FromString,
          response_serializer=f99__erp__api__pb2.CreateSaleOrderResult.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'f99_erp_api.F99ErpApi', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
