
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-13T14:08:40-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "b6e8b0be4d672f009ccde2874e0eb4bcd4356f39",
 "version": "0.1.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
