# (C) Copyright 2007-2021 Enthought, Inc., Austin, TX
# All rights reserved.
#
# This software is provided without warranty under the terms of the BSD
# license included in LICENSE.txt and may be redistributed only under
# the conditions described in the aforementioned license. The license
# is also available online at http://www.enthought.com/licenses/BSD.txt
#
# Thanks for using Enthought open source!

"""
Version information for this Envisage distribution.

This file is autogenerated by the Envisage setup.py script.
"""

#: The full version of the package, including a development suffix
#: for unreleased versions of the package.
version = "6.0.1"

#: The Git revision from which this release was made.
git_revision = "92ae3280d782b34ad96ba16ef1089281d5687223"

#: Flag whether this is a final release
is_released = True
