
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-14T21:05:05+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "1371e80f0ccf7737a639fab4d5b884e37915de62",
 "version": "2021.05.06post11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
