[tool.poetry]
name = "pyfixedwidths"
version = "0.1.0"
description = "Easy way converting from text, list, or dict to text or list with fixed widths."
readme = "README.rst"
authors = ["Shoma FUKUDA <fkshom+pypi@gmail.com>"]
homepage = "https://github.com/fkshom"
repository = "https://github.com/fkshom/pyfixedwidths"
documentation = "https://github.com/fkshom/pyfixedwidths/wiki"
license = "MIT"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    'Programming Language :: Python :: 3',
    "Programming Language :: Python :: 3.6",
    "Topic :: Utilities",
]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-watch = "^4.2.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
