
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-11T14:15:21+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "cfca11652c663a8a31b07ec49d31031eca817792",
 "version": "1.0.0rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
