[tool.poetry]
name = "understory-code"
version = "0.0.44"
description = "Tools for metamodern software development"
authors = ["Angelo Gladding <angelo@lahacker.net>"]
license = "AGPL-3.0-or-later"
readme = "README.md"
packages = [
    { include = "understory" }
]

[tool.poetry.urls]
Homepage = "https://github.com/canopy/understory-code"

[tool.poetry.scripts]
pkg = "understory.pkg.__main__:main"

[tool.poetry.dependencies]
python = "^3.7"
radon = "^4.5.1"
pendulum = "^2.1.2"
sh = "^1.14.2"
semver = "^2.13.0"
understory-term = "*"

[tool.poetry.dev-dependencies]
ipython = "^7.23.1"
flake8 = "^3.9.2"
flake8-docstrings = "^1.6.0"
pep8-naming = "^0.11.1"
pytest = "^6.2.4"
pytest-cov = "^2.12.0"
black = "^21.5b2"
pyre-check = "^0.9.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
