#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['expositor', 'expositor.cli', 'expositor.cli.converter']

package_data = \
{'': ['*']}

package_dir = \
{'': 'src'}

extras_require = \
{'all': ['requests >=2.24.0,<3.0.0',
         'quo >=2021.5.15',
         'XlsxWriter',
         'colorama']}

setup(name='expositor',
      version='2021.6.dev1',
      description='Shodan CLI',
      author='Gerrishon Sirere.',
      author_email='secretum.inc@pm.me',
      url='https://github.com/secretum-inc/expositor',
      packages=packages,
      package_data=package_data,
      package_dir=package_dir,
      extras_require=extras_require,
      python_requires='>=3.6',
     )
