
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-16T10:46:15-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "c5c01a0f4c78a8716d2040b190e5a81b97edc298",
 "version": "0.4.15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
