
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-17T11:33:15+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "f5c55502881c2ff8b6be30426061a2ef490d9caa",
 "version": "1.0.6rc5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
