
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-12T01:07:40+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "8833705ecc247983a2e08b031c3ddd7e15a0bf61",
 "version": "0.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
