[tool]
[tool.poetry]
name = "techlib-nr-common"
version = "3.0.0a48"
description = "NR common data types"
license = "MIT"
keywords = ["National", "Repository", "common", "model", "Invenio"]
classifiers = ["Environment :: Web Environment", "Intended Audience :: Developers", "License :: OSI Approved :: MIT License", "Operating System :: OS Independent", "Programming Language :: Python", "Topic :: Internet :: WWW/HTTP :: Dynamic Content", "Topic :: Software Development :: Libraries :: Python Modules", "Programming Language :: Python :: 3", "Programming Language :: Python :: 3.9", "Development Status :: 3 - Alpha"]
authors = ["Daniel Kopecký <Daniel.Kopecky@techlib.cz>", "Denys Chaplyhin <chaplyhd@vscht.cz>"]
readme = "README.md"
packages = [{ include = "nr_common" }]

[tool.poetry.dependencies]
python = "^3.8"
idutils = "^1.1.8"
isbnlib = "^3.10.3"
sphinx = { version = "^1.5.1", optional = true }
python-stdnum = "^1.16"
oarepo-invenio-model = "^2.0.0"
oarepo-search = "^1.0.0"
techlib-nr-common-metadata = "^3.0.0a48"

[tool.poetry.dev-dependencies]
pytest = "^5.0.0"
pytest-cov = "^2.10.1"
oarepo = "^3.3"
oarepo-ui = "^2.3.0"
oarepo-micro-api = "^3.3.60"
oarepo-mapping-includes = "<=1.2.0"
oarepo-multilingual = "^2.5.0"
oarepo-taxonomies = "^3.0.0a1"
oarepo-references = "^1.9.0"
oarepo-records-draft = "^5.0.0a7"
pytest-runner = "^5.3.0"
oarepo-fsm = "^1.5.0"
oarepo-communities = "^1.3.4"

[tool.poetry.extras]
docs = ["sphinx"]

[tool.poetry.plugins."invenio_jsonschemas.schemas"]
"nr_common" = "nr_common.jsonschemas"

[tool.poetry.plugins."invenio_db.alembic"]
"nr_common" = "nr_common:alembic"

[tool.poetry.plugins."oarepo_mapping_includes"]
"nr_common" = "nr_common.mapping_includes"

