
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-09T14:44:06+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "2a53507aa3ab1d1d0034c999d89caf478a57ec23",
 "version": "1.4.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
