[package]
name = "h3ron"
description = "high level rust API including collections for selected parts of H3"
version = "0.11.0"
authors = ["Nico Mandery <nico@nmandery.net>"]
edition = "2018"
license = "MIT"
keywords = ["geo", "spatial", "h3"]
readme = "../README.md"
homepage = "https://github.com/nmandery/h3ron"
repository = "https://github.com/nmandery/h3ron"

[dependencies]
geo = "^0.18"
itertools = "^0.10"
# Error handling
thiserror = "1.0"
svgbobdoc = "^0.2"

[dependencies.h3ron-h3-sys]
path = "../h3ron-h3-sys"
version = "0.11.0" # for publishing on crates.io

[dependencies.geo-types]
version = "^0.7"

[dependencies.serde]
version = "^1.0"
features = [ "derive" ]

[dev-dependencies]
bincode = "^1.3"

[dev-dependencies.geojson]
version = "^0.22"
features = [
    "geo-types"
]
