# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ondewo/nlu/knowledge_base.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ondewo.survey import survey_pb2 as ondewo_dot_survey_dot_survey__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ondewo/nlu/knowledge_base.proto',
  package='ondewo.nlu',
  syntax='proto3',
  serialized_options=b'\n\036com.google.cloud.dialogflow.v2B\022KnowledgeBaseProtoP\001ZDgoogle.golang.org/genproto/googleapis/cloud/dialogflow/v2;dialogflow\370\001\001\242\002\002DF\252\002\032Google.Cloud.Dialogflow.V2',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1fondewo/nlu/knowledge_base.proto\x12\nondewo.nlu\x1a\x1aondewo/survey/survey.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"=\n\x14PersistSurveyRequest\x12%\n\x06survey\x18\x01 \x01(\x0b\x32\x15.ondewo.survey.Survey\"\'\n\x12\x45raseSurveyRequest\x12\x11\n\tsurvey_id\x18\x01 \x01(\t\"*\n\x15RetrieveSurveyRequest\x12\x11\n\tsurvey_id\x18\x01 \x01(\t\"?\n\x16RetrieveSurveyResponse\x12%\n\x06survey\x18\x01 \x01(\x0b\x32\x15.ondewo.survey.Survey2\xdb\x02\n\rKnowledgeBase\x12`\n\rPersistSurvey\x12 .ondewo.nlu.PersistSurveyRequest\x1a\x16.google.protobuf.Empty\"\x15\x82\xd3\xe4\x93\x02\x0f\"\n/v2/survey:\x01*\x12y\n\x0eRetrieveSurvey\x12!.ondewo.nlu.RetrieveSurveyRequest\x1a\".ondewo.nlu.RetrieveSurveyResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v2/survey/{survey_id=*}\x12m\n\x0b\x45raseSurvey\x12\x1e.ondewo.nlu.EraseSurveyRequest\x1a\x16.google.protobuf.Empty\"&\x82\xd3\xe4\x93\x02 \x12\x1e/v2/survey/{survey_id=*}/eraseB\xa1\x01\n\x1e\x63om.google.cloud.dialogflow.v2B\x12KnowledgeBaseProtoP\x01ZDgoogle.golang.org/genproto/googleapis/cloud/dialogflow/v2;dialogflow\xf8\x01\x01\xa2\x02\x02\x44\x46\xaa\x02\x1aGoogle.Cloud.Dialogflow.V2b\x06proto3'
  ,
  dependencies=[ondewo_dot_survey_dot_survey__pb2.DESCRIPTOR,google_dot_api_dot_annotations__pb2.DESCRIPTOR,google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_PERSISTSURVEYREQUEST = _descriptor.Descriptor(
  name='PersistSurveyRequest',
  full_name='ondewo.nlu.PersistSurveyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='survey', full_name='ondewo.nlu.PersistSurveyRequest.survey', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=195,
)


_ERASESURVEYREQUEST = _descriptor.Descriptor(
  name='EraseSurveyRequest',
  full_name='ondewo.nlu.EraseSurveyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='survey_id', full_name='ondewo.nlu.EraseSurveyRequest.survey_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=197,
  serialized_end=236,
)


_RETRIEVESURVEYREQUEST = _descriptor.Descriptor(
  name='RetrieveSurveyRequest',
  full_name='ondewo.nlu.RetrieveSurveyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='survey_id', full_name='ondewo.nlu.RetrieveSurveyRequest.survey_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=238,
  serialized_end=280,
)


_RETRIEVESURVEYRESPONSE = _descriptor.Descriptor(
  name='RetrieveSurveyResponse',
  full_name='ondewo.nlu.RetrieveSurveyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='survey', full_name='ondewo.nlu.RetrieveSurveyResponse.survey', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=282,
  serialized_end=345,
)

_PERSISTSURVEYREQUEST.fields_by_name['survey'].message_type = ondewo_dot_survey_dot_survey__pb2._SURVEY
_RETRIEVESURVEYRESPONSE.fields_by_name['survey'].message_type = ondewo_dot_survey_dot_survey__pb2._SURVEY
DESCRIPTOR.message_types_by_name['PersistSurveyRequest'] = _PERSISTSURVEYREQUEST
DESCRIPTOR.message_types_by_name['EraseSurveyRequest'] = _ERASESURVEYREQUEST
DESCRIPTOR.message_types_by_name['RetrieveSurveyRequest'] = _RETRIEVESURVEYREQUEST
DESCRIPTOR.message_types_by_name['RetrieveSurveyResponse'] = _RETRIEVESURVEYRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PersistSurveyRequest = _reflection.GeneratedProtocolMessageType('PersistSurveyRequest', (_message.Message,), {
  'DESCRIPTOR' : _PERSISTSURVEYREQUEST,
  '__module__' : 'ondewo.nlu.knowledge_base_pb2'
  # @@protoc_insertion_point(class_scope:ondewo.nlu.PersistSurveyRequest)
  })
_sym_db.RegisterMessage(PersistSurveyRequest)

EraseSurveyRequest = _reflection.GeneratedProtocolMessageType('EraseSurveyRequest', (_message.Message,), {
  'DESCRIPTOR' : _ERASESURVEYREQUEST,
  '__module__' : 'ondewo.nlu.knowledge_base_pb2'
  # @@protoc_insertion_point(class_scope:ondewo.nlu.EraseSurveyRequest)
  })
_sym_db.RegisterMessage(EraseSurveyRequest)

RetrieveSurveyRequest = _reflection.GeneratedProtocolMessageType('RetrieveSurveyRequest', (_message.Message,), {
  'DESCRIPTOR' : _RETRIEVESURVEYREQUEST,
  '__module__' : 'ondewo.nlu.knowledge_base_pb2'
  # @@protoc_insertion_point(class_scope:ondewo.nlu.RetrieveSurveyRequest)
  })
_sym_db.RegisterMessage(RetrieveSurveyRequest)

RetrieveSurveyResponse = _reflection.GeneratedProtocolMessageType('RetrieveSurveyResponse', (_message.Message,), {
  'DESCRIPTOR' : _RETRIEVESURVEYRESPONSE,
  '__module__' : 'ondewo.nlu.knowledge_base_pb2'
  # @@protoc_insertion_point(class_scope:ondewo.nlu.RetrieveSurveyResponse)
  })
_sym_db.RegisterMessage(RetrieveSurveyResponse)


DESCRIPTOR._options = None

_KNOWLEDGEBASE = _descriptor.ServiceDescriptor(
  name='KnowledgeBase',
  full_name='ondewo.nlu.KnowledgeBase',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=348,
  serialized_end=695,
  methods=[
  _descriptor.MethodDescriptor(
    name='PersistSurvey',
    full_name='ondewo.nlu.KnowledgeBase.PersistSurvey',
    index=0,
    containing_service=None,
    input_type=_PERSISTSURVEYREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=b'\202\323\344\223\002\017\"\n/v2/survey:\001*',
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RetrieveSurvey',
    full_name='ondewo.nlu.KnowledgeBase.RetrieveSurvey',
    index=1,
    containing_service=None,
    input_type=_RETRIEVESURVEYREQUEST,
    output_type=_RETRIEVESURVEYRESPONSE,
    serialized_options=b'\202\323\344\223\002\032\022\030/v2/survey/{survey_id=*}',
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='EraseSurvey',
    full_name='ondewo.nlu.KnowledgeBase.EraseSurvey',
    index=2,
    containing_service=None,
    input_type=_ERASESURVEYREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=b'\202\323\344\223\002 \022\036/v2/survey/{survey_id=*}/erase',
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_KNOWLEDGEBASE)

DESCRIPTOR.services_by_name['KnowledgeBase'] = _KNOWLEDGEBASE

# @@protoc_insertion_point(module_scope)
