# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from ondewo.nlu import knowledge_base_pb2 as ondewo_dot_nlu_dot_knowledge__base__pb2


class KnowledgeBaseStub(object):
    """///// Services ///////

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PersistSurvey = channel.unary_unary(
                '/ondewo.nlu.KnowledgeBase/PersistSurvey',
                request_serializer=ondewo_dot_nlu_dot_knowledge__base__pb2.PersistSurveyRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.RetrieveSurvey = channel.unary_unary(
                '/ondewo.nlu.KnowledgeBase/RetrieveSurvey',
                request_serializer=ondewo_dot_nlu_dot_knowledge__base__pb2.RetrieveSurveyRequest.SerializeToString,
                response_deserializer=ondewo_dot_nlu_dot_knowledge__base__pb2.RetrieveSurveyResponse.FromString,
                )
        self.EraseSurvey = channel.unary_unary(
                '/ondewo.nlu.KnowledgeBase/EraseSurvey',
                request_serializer=ondewo_dot_nlu_dot_knowledge__base__pb2.EraseSurveyRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class KnowledgeBaseServicer(object):
    """///// Services ///////

    """

    def PersistSurvey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetrieveSurvey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EraseSurvey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KnowledgeBaseServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PersistSurvey': grpc.unary_unary_rpc_method_handler(
                    servicer.PersistSurvey,
                    request_deserializer=ondewo_dot_nlu_dot_knowledge__base__pb2.PersistSurveyRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'RetrieveSurvey': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrieveSurvey,
                    request_deserializer=ondewo_dot_nlu_dot_knowledge__base__pb2.RetrieveSurveyRequest.FromString,
                    response_serializer=ondewo_dot_nlu_dot_knowledge__base__pb2.RetrieveSurveyResponse.SerializeToString,
            ),
            'EraseSurvey': grpc.unary_unary_rpc_method_handler(
                    servicer.EraseSurvey,
                    request_deserializer=ondewo_dot_nlu_dot_knowledge__base__pb2.EraseSurveyRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ondewo.nlu.KnowledgeBase', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class KnowledgeBase(object):
    """///// Services ///////

    """

    @staticmethod
    def PersistSurvey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ondewo.nlu.KnowledgeBase/PersistSurvey',
            ondewo_dot_nlu_dot_knowledge__base__pb2.PersistSurveyRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RetrieveSurvey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ondewo.nlu.KnowledgeBase/RetrieveSurvey',
            ondewo_dot_nlu_dot_knowledge__base__pb2.RetrieveSurveyRequest.SerializeToString,
            ondewo_dot_nlu_dot_knowledge__base__pb2.RetrieveSurveyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EraseSurvey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ondewo.nlu.KnowledgeBase/EraseSurvey',
            ondewo_dot_nlu_dot_knowledge__base__pb2.EraseSurveyRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
