
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-15T08:47:45+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "8c6e8f2298ff6b62f4db281517a52cd96b75a5d4",
 "version": "2.6.0.18"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
