"""
    DataMeta

    DataMeta  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Contact: leon.kuchenbecker@uni-tuebingen.de
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import datameta_client_lib
from datameta_client_lib.model.identifier import Identifier
globals()['Identifier'] = Identifier
from datameta_client_lib.model.user_response_group import UserResponseGroup


class TestUserResponseGroup(unittest.TestCase):
    """UserResponseGroup unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserResponseGroup(self):
        """Test UserResponseGroup"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UserResponseGroup()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
