"""
    DataMeta

    DataMeta  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Contact: leon.kuchenbecker@uni-tuebingen.de
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import datameta_client_lib
from datameta_client_lib.model.user_response_group import UserResponseGroup
globals()['UserResponseGroup'] = UserResponseGroup
from datameta_client_lib.model.register_settings_response import RegisterSettingsResponse


class TestRegisterSettingsResponse(unittest.TestCase):
    """RegisterSettingsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRegisterSettingsResponse(self):
        """Test RegisterSettingsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RegisterSettingsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
