
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-14T09:32:25+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "6523afbdd8357fbf7d93a3dfe94fc9d7d8290739",
 "version": "0.7.0.post.dev194"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
