[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "xmltodict",
    "dicttoxml",
    "Django>=3",
    "djangorestframework>=3",
    "python-dotenv",
]
build-backend = "setuptools.build_meta"
