
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-11T12:31:43-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "6af57f4283fcbfe8d9c6350afd0dd643fe3ca3ed",
 "version": "0.8.299"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
