#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['drf_pyjwt']

package_data = \
{'': ['*']}

install_requires = \
['pyjwt>=2.1,<3', 'django>=3.1', 'djangorestframework>=3.10', 'cryptography<4']

setup(name='drf_pyjwt',
      version='0.0.8',
      description='A JSON Web Token authentication extension for the Django REST Framework.',
      author='Vicheslav Krachkov',
      author_email='vskrachkov@gmail.com',
      url='https://github.com/vskrachkov/drf_pyjwt',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      python_requires='>=3.8',
     )
