
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-16T11:02:59+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "e20a9f987e9912e70751875e4cf401026d6ec075",
 "version": "1.1.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
