
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-16T10:44:25-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "7fb3d17a64b8b00f64ac80f59da81bc546911bed",
 "version": "0.16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
