[tool.poetry]
name = "delt"
version = "0.1.12"
description = "A python brige to use arkitekt in your Djangop Application"
packages = [{include = "delt"}]
authors = ["jhnnsrs <jhnnsrs@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
Django = "^3.2"
bergen = "^0.4.69"
PyYAML = "^5.4.1"
django-rest-framework = "^0.1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
