
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-16T09:26:47+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "cebc0d17603d7171c39568307d7b87ba0b6d6782",
 "version": "2496"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
