#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['flask_verify']

package_data = \
{'': ['*']}

install_requires = \
['flask']

setup(name='flask_verify',
      version='0.1.2',
      description='Used to verify Flask route Response and Request contents.',
      author='Ege Ozkan',
      author_email='egeemirozkan24@gmail.com',
      url='https://github.com/ambertide/flask-verify',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      python_requires='>=3.9',
     )
