
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-14T18:35:07+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "193723c96cba70a65d5a1f7481564534348e1ae1",
 "version": "0.20.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
