
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-14T10:41:18+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "e487168ab2794eb9a31022b5c00664665deeb00a",
 "version": "2493"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
