# ******************************************************************************
#
# django-loader, a configuration and secret loader for Django
#
# Copyright (C) 2021 Jeremy A Gray <gray@flyquackswim.com>.
#
# SPDX-License-Identifier: MIT
#
# ******************************************************************************

[build-system]

# Setuptools.
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

# Poetry.
# requires = ["poetry_core>=1.0.0"]
# build-backend = "poetry.core.masonry.api"

[tool]

[tool.black]

line-length = 88
target-version = ['py38']
include = '\.pyi?$'
exclude = '''
(
  /(
    \.git
    | \.pytest_cache
    | __pycache__
    | htmlcov
  )/
)
'''
force_exclude = '.*/migrations/.*'

[tool.coverage.run]

omit = ["*migrations*"]

[tool.isort]

ensure_newline_before_comments = true
force_single_line = true
include_trailing_comma = true
line_length = 88
multi_line_output = 3
use_parentheses = true
skip = "migrations"

[tool.pccc]

header_length = 50
body_length = 72
rewrap = false
spell_check = false
repair = false

types = [
"build",
"ci",
"db",
"depends",
"deploy",
"docs",
"feat",
"fix",
"graphics",
"layout",
"perf",
"refactor",
"style",
"test"
]

scopes = [
"loader",
"fake",
]

footers = [
"signed-off-by"
]

required_footers = [
"signed-off-by"
]

[tool.poetry]

authors = ["Jeremy A Gray <jeremy.a.gray@gmail.com>"]
description = "django-loader:  a configuration and secret loader for Django"
name = "django-loader"
version = "0.0.2"
license = "MIT"
maintainers = ["Jeremy A Gray <gray@flyquackswim.com>"]
readme = "README.rst"
homepage = "https://github.com/jeremyagray/django-loader"
repository = "https://github.com/jeremyagray/django-loader"

classifiers = [
  "Development Status :: 3 - Alpha",
  "Environment :: Console",
  "Framework :: Django :: 2.2",
  "Framework :: Django :: 3.2",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3.6",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Topic :: Internet :: WWW/HTTP :: Site Management",
]

packages = [
  { include = "loader" },
]

include = [
  "README.rst",
  "docs/*.*",
]

[tool.poetry.dependencies]

Django = "^3.2"
bespon = "^0.6.0"
python = "^3.9"
"ruamel.yaml" = "^0.17.9"
toml = "^0.10"

[tool.poetry.dev-dependencies]

Sphinx = "^3.4"
black = { version = "*", allow-prereleases = true }
flake8 = "^3.8"
flake8-docstrings = "^1.5"
isort = "^5.6"
hypothesis = "^6.9.0"
pccc = "^0.4"
pre-commit = "^2.9"
pytest = "^6.1"
pytest-cov = "^2.10"
pytest-django = "^4.1"
twine = "^3.4.1"

[tool.poetry.scripts]

django-loader = "loader:main"

[tool.poetry.urls]

"Issues" = "https://github.com/jeremyagray/django-loader/issues"
"Documentation" = "https://django-loader.readthedocs.io/"
"Repository" = "https://github.com/jeremyagray/django-loader"

[tool.pytest.ini_options]

DJANGO_SETTINGS_MODULE = "fake.settings"

flake8-max-complexity = 20
flake8-max-line-length = 88

flake8-ignore = [
    "* E203, W503",
    "__init__.py F401",
]
