# `haystac config` defaults
cache:
  ~/haystac/cache/
mismatch_probability:
  0.15
bowtie2_scaling:
  25.0
use_conda:
  False  # turn off by default, as dependencies will be installed by the conda package

# `haystac database` defaults
rank:
  'species'
seed:
  null
cores:
  all
mem:
  all
bowtie2_threads_db:
  4

# `haystac sample` defaults
collapse:
  False
trim_adapters:
  True
min_prob:
  0.5
bowtie2_threads_aln:
  4
mapdamage:
  False