# Generated by Django 2.2.19 on 2021-06-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoped_rbac', '0005_auto_20210104_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='rbac_context',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='roleassignment',
            name='rbac_context',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
    ]
