
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-13T16:31:53+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "3525ac810ae03709d6dad3257e16bbf8fa7f2ec4",
 "version": "2021.05.06post4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
