[tool.poetry]
name = "hexaa-utils"
version = "0.1.0"
description = ""
authors = ["Song <songhe@hexaa.com>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "hexaa-pypi"
url = "http://origin.hexaa.com:8081/nexus/repository/hexaa-pypi"
