
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-10T18:44:52+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "3aa7096e3305423e7b66dc46a71b85ee1b4f784a",
 "version": "2.9.32"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
