
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-10T06:27:53-1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "54b53cd94b02fa1e071ef12f6fb2a4761010e450",
 "version": "1.34.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
