[tool.poetry]
name = "snit"
version = "0.1.1"
description = "Python command line application to backup IDE / code editor settings. "
authors = ["Norman Lorrain <normanlorrain@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/normanlorrain/snit"
classifiers = [
    "Topic :: Software Development"
]

[tool.poetry.dependencies]
python = "^3.9"
click = "^8.0.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^21.5b2"


[tool.poetry.scripts]
snit = "snit.cli:cli"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 95
target-version = [ "py39",]
