
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-14T09:00:43+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "76d196a544c12e8dd7530d30200380c128c9717e",
 "version": "0.7.0.post.dev186"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
