[tool.poetry]
name = "apteryx"
version = "0.1.2"
description = "Utilities and useful things for Apteryx Labs"
authors = ["apteryxlabs <matthew@apteryxlabs.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
google-api-python-client = "^2.8.0"
google-auth-httplib2 = "^0.1.0"
google-auth-oauthlib = "^0.4.4"
google-cloud-storage = "^1.38.0"
tqdm = "^4.61.0"
numpy = "^1.20.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
