
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-16T10:27:16+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "8d2f39ad8fa59dffcc300a6f8cd5c855e6a2810a",
 "version": "0.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
