
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-16T15:38:06+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "5a2c7af9f7ec7138c9ba3802144a2c984cd3a35a",
 "version": "v1.0.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
