
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-13T00:18:52+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "28c2d74b4b5302ff88280b1f9f572d1a9ac5082b",
 "version": "0.7.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
