[tool.poetry]
name = "docker-cli"
version = "1.0.2"
description = "A straight forward tool to get information from docker command line and try to parse into json format as far as possible."
authors = ["Manu <grajmanu@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/manugraj/docker-cli"
documentation = "https://github.com/manugraj/docker-cli"
keywords = ["docker", "docker-compose"]
classifiers = [
    "Topic :: Software Development"
]

[tool.poetry.dependencies]
python = "^3.6"
docker-compose = "^1.29.2"
"delegator.py" = "^0.1.1"
Unidecode = "^1.2.0"
clean-text = "^0.4.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
