
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-09T15:00:23+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "d21a852d4e0b094a965c0c13efdb23c2a9c1a5df",
 "version": "1.3.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
