
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-10T05:13:14+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "a42a321b378e4dc177ca9d881e1a0d06083843be",
 "version": "0.7.0.post.dev170"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
