
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-13T18:46:37+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "d616f6c32fe0e3716f4a03e476189ff266840165",
 "version": "0.27.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
