
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-11T15:28:14-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "6ce372c77b49133097e9d08397c63c99a18ad319",
 "version": "4.3.42"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
