
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-14T09:42:40+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "20be85e64adf887e0eb5c88dec2a38e0e5356d6c",
 "version": "0.6.0rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
