
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-10T13:59:48+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "b60a28e4c67a80bf407dc47c30a2d7260f83af0a",
 "version": "1.3.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
