
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-16T10:16:37+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "8831d0fc23c94bea119061a5a6e314ea3c2034ab",
 "version": "0.9.17"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
