
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-09T12:56:19-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "cd085528629b7aa650cc9bfb7ab6e8a805c13644",
 "version": "v1.4.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
