
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-10T07:27:09+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "bff8001c4f3534c4dea92ed35e05766ea45aea5a",
 "version": "0.7.0.post.dev178"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
