#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['observattr']

package_data = \
{'': ['*']}

package_dir = \
{'': 'src'}

setup(name='observattr',
      version='21.6',
      description='Observable class attributes in pure python',
      author='Marnix Bockstael',
      author_email='mbockstael@protonmail.com',
      url='https://github.com/mbckstl/observattr',
      packages=packages,
      package_data=package_data,
      package_dir=package_dir,
     )
