[build-system]
requires = [ "whey",]
build-backend = "whey"

[project]
name = "yapf-isort"
version = "0.6.0"
description = "yapf 💌 isort"
readme = "README.rst"
keywords = []
dynamic = []
dependencies = [
    "asttokens>=2.0.4",
    "click>=7.1.2",
    "consolekit>=0.3.0",
    "domdf-python-tools>=0.10.0",
    "formate>=0.4.5",
    "isort<=5.6.4,>=5.5.2",
    "yapf<0.32.0,>=0.30.0",
]
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: Implementation :: CPython",
    "Typing :: Typed",
]
requires-python = ">=3.6"

[[project.authors]]
name = "Dominic Davis-Foster"
email = "dominic@davis-foster.co.uk"


[project.license]
file = "LICENSE"

[project.urls]
Homepage = "https://github.com/domdfcoding/yapf-isort"
"Issue Tracker" = "https://github.com/domdfcoding/yapf-isort/issues"
"Source Code" = "https://github.com/domdfcoding/yapf-isort"

[project.scripts]
yapf_isort = "yapf_isort.__main__:main"
yapf-isort = "yapf_isort.__main__:main"

[tool.mkrecipe]
conda-channels = [ "conda-forge", "domdfcoding",]
extras = "all"
license-key = "Apache-2.0"
package = "yapf_isort"

[tool.whey]
base-classifiers = [ "Typing :: Typed",]
python-versions = [ "3.6", "3.7", "3.8", "3.9",]
python-implementations = [ "CPython",]
platforms = [ "Windows", "macOS", "Linux",]
license-key = "Apache-2.0"
package = "yapf_isort"
