# Generated by Django 2.2.6 on 2021-02-26 18:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchensink', '0018_auto_20210224_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiedoc',
            name='author',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='author',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
