# Generated by Django 2.2 on 2021-03-16 19:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchensink', '0019_auto_20210226_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiedoc',
            name='validation_schema',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='JSON Schema', null=True),
        ),
        migrations.AlterField(
            model_name='formcontent',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='validation_schema',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='JSON Schema', null=True),
        ),
    ]
