# Generated by Django 2.2 on 2021-03-25 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchensink', '0021_auto_20210316_1936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archiedoc',
            old_name='author',
            new_name='favorites',
        ),
        migrations.RenameField(
            model_name='formcontent',
            old_name='author',
            new_name='favorites',
        ),
        migrations.RenameField(
            model_name='sheet',
            old_name='author',
            new_name='favorites',
        ),
    ]
