# Generated by Django 2.2 on 2021-05-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchensink', '0022_auto_20210325_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiedoc',
            name='custom_slug',
            field=models.CharField(blank=True, help_text="DANGEROUS! Make sure that this ID does not conflict with existing data or content may be lost! Remember most Google doc slugs end with 'data.json'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='formcontent',
            name='custom_slug',
            field=models.CharField(blank=True, help_text="DANGEROUS! Make sure that this ID does not conflict with existing data or content may be lost! Remember most form slugs start with '/forms/' and end with 'data.json'.", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sheet',
            name='custom_slug',
            field=models.CharField(blank=True, help_text="DANGEROUS! Make sure that this ID does not conflict with existing data or content may be lost! Remember most Google doc slugs end with 'data.json'", max_length=100, null=True),
        ),
    ]
