
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-14T14:37:59+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "cb6631d1f76b50dc207c599471aec495a7dd3fc3",
 "version": "2021.05.06post7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
