[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "lumache"
author = "Juan Luis Cano Rodríguez"
author-email = "juanlu@readthedocs.org"
home-page = ""
