MONGO_NAME=test
MONGO_HOST=localhost
MONGO_PORT=
MONGO_USER=
MONGO_PASSWORD=

#SENTRY
SENTRY_DSN=

#AWS
AWS_STORAGE_BUCKET_NAME=test
SNS_ENDPOINT_SUBSCRIBE=
TOPIC_SNS_VERA=
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_REGION=us-west-2