
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-10T04:31:36+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "38c1cb748c5303a8b34d981c6d548cf19113b073",
 "version": "2.6.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
