
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-14T09:24:11+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "c74f1bfaac9457196e97b902789e85df62f92d83",
 "version": "0.7.0.post.dev192"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
