[metadata]
description-file = "README.md"

[build-system]
requires = ["poetry>=1.1,<2", "virtualenv==20.0.33", "wheel>=0.36,<1.0"]
build-backend = "poetry.masonry.api"


#########################################################################################
# Poetry metadata
#########################################################################################

[tool.poetry]
name = "decorateme"
version = "0.2.1"
description = "Python decorators for str/repr, equality, immutability, and more."
keywords = ["python", "decorators", "repr"]
authors = ["Douglas Myers-Turnbull"]
maintainers = ["Douglas Myers-Turnbull"]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://github.com/dmyersturnbull/decorate-me"
repository = "https://github.com/dmyersturnbull/decorate-me"
documentation = "https://decorate-me.readthedocs.io"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Natural Language :: English",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
	"Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules"
]

[tool.poetry.urls]
CI = "https://github.com/dmyersturnbull/decorate-me/actions"
Issues = "https://github.com/dmyersturnbull/decorate-me/issues"
Download = "https://pypi.org/project/decorate-me/"


#########################################################################################
# Poetry build & dependencies
#########################################################################################

[tool.poetry.dependencies]
python                   = "^3.8"

[tool.poetry.dev-dependencies]
black                    = "==21.5b2"
pre-commit               = "^2.13"
pre-commit-hooks         = "^4.0"
bandit                   = "^1.7"
pytest                   = "^6.2"
coverage                 = {extras = ["toml"], version = "^5.5"}
pytest-cov               = "^2.11"
flake8                   = "^3.9"
flake8-docstrings        = "^1.5"
flake8-bugbear           = ">=21"
sphinx-copybutton        = ">=0.3, <1.0"
sphinx-autoapi           = "^1.5"
sphinx-rtd-theme         = ">=0.5, <1.0"
tomlkit                  = ">=0.7, <1.0"
typer                    = ">=0.3, <1.0"


#########################################################################################
# Tyrannosaurus
#########################################################################################

[tool.tyrannosaurus.options]
align    = true

[tool.tyrannosaurus.sources]
status             = "'Development'"
date               = "'2020-08-24'"
copyright          = "'Copyright 2017–2021'"
version            = "tool.poetry.version"
release            = "tool.poetry.version"
pyversions         = "tool.poetry.dependencies"
devdeps            = "tool.poetry.dev-dependencies"
linelength         = "tool.black.line-length"
authors = [
    "Douglas Myers-Turnbull <github:dmyersturnbull,orcid:0000-0003-3610-4808>"
]
contributors = []
maintainers = "tool.tyrannosaurus.sources.authors"

[tool.tyrannosaurus.targets]
# these are file and directory names, without filename extensions
# they will only be synced if they exist; never created
# to get a recipe and anaconda env, run 'tyrannosaurus recipe' and 'tyrannosaurus env'
pyproject    = true
init         = true
tox          = true
docs         = true
recipes      = true
license      = true
authors      = true
github       = true
readme       = true
changelog    = true
environment  = false


#########################################################################################
# Testing
#########################################################################################

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "INFO"
log_cli_format = "%(asctime)s [%(levelname)8s] %(name)s: %(message)s (%(filename)s:%(lineno)s)"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"


#########################################################################################
# Style checking
#########################################################################################

[tool.coverage.paths]
source = ["decorateme"]

[tool.coverage.run]
source = ["decorateme"]

[tool.coverage.report]
show_missing = true

[tool.black]
line-length = 100
target-version = ["py38"]
