#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['cryptool']

package_data = \
{'': ['*'], 'cryptool': ['exchanges/*']}

install_requires = \
['pandas>=1.2.4', 'python-binance>=1.0.12']

setup(name='cryptool',
      version='0.0.3',
      description='cryptool is a python library to more easily deal with crypto exchanges',
      author='Carlo Perassi',
      author_email='carlo.perassi@gmail.com',
      url='https://github.com/carlok/cryptool',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      python_requires='>=3.8',
     )
