
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-14T09:08:32+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "599d992ff97daa7ab741b533d7126c63697d4449",
 "version": "0.7.0.post.dev188"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
