
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-09T23:20:11+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "2d2e11f5dc71523b1c3b41f7d7ba7bd9694b3fea",
 "version": "0.4.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
