
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-09T16:18:05+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "a3d81dbb89bb109ac8a01a627ca0118cfa295ea5",
 "version": "0.2.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
