
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-16T15:56:36+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "be94bed9a62239a11a0ccb2894c6caea51d56125",
 "version": "v0.12.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
